<h1 style="color:blue;text-align:center"> Pandas </h1>
<h3 style="color:black;text-align:center"> Chih-Hung Lai  <br />
Date of establishment: 2017.11.05  
Last Modified Date: 2022.03.17</h3>

<h2 style="color:blue"> Content of Table </h2>

1. Introduction
 1.1 Advanced References  
 1.2 What is pandas?  
 1.3 Difference between Numpy and Pandas?  
2. Series: one dimensional arrays in Pandas  
 2.1 Series creation and index use  
 2.2 Elements and data types in Series  
 2.3 Properties and methods about basic information  
 2.4 Operation of Series  
3. DataFrame  
 3.1 Features of DataFrames  
 3.2 Establishment of DataFrames  
 3.3 Display DataFrame basic information   
 3.4 Rows, Columns & Index  
4. Access elements in DataFrames  
 4.1 From Rows & Columns  
 4.2 From boolean statement
5. Visit DataFrame  
6. Update, merge and delete DataFrame elements  
 6.1 Update data  
 6.2 Delete data  
 6.3 Add data  
 6.4 Duplicate, concatenate and merge data  
7. Access files 

# 1 Introduction

## 1.1 Advanced References

- Official website
    - https://pandas.pydata.org/
* W3School website
    - https://www.w3schools.com/python/pandas/default.asp

## 1.2 What is pandas?

- Pandas is a Python library used for working with data sets.

- It has functions for analyzing, cleaning, exploring, and manipulating data.

- The name "Pandas" has a reference to both "PANel DAta" and was created by Wes McKinney in 2008.

- Common alias of pandas is pd

## 1.3 Difference between Numpy and Pandas?

1. Numpy is in the form of an array, there is no field name or label, and the data type must be the same 
    - Pandas have column labels and index labels (or index numbers), and can be different data types in different columns 
    - The Pandas module mainly works with the tabular data, whereas the NumPy module works with the numerical data.
2. Pandas is built based on Numpy, with list labels, and the data types can be different

3. Pandas is built on top of the NumPy package, which means Numpy is required for operating the Pandas. 

- Reference 
    - https://www.javatpoint.com/pandas-vs-numpy

In [424]:
# elements in one array of numpy are only one data type 

import numpy as np

a = np.array([[10, 20, 30], [10, 10, 40]])   # only contain integers
print(a, '\n')
print(a.dtype)
print(a[1,1].dtype)
print(a[0].dtype)

print()
a = np.array([[10, 20.3, 30], [10, 10, 40]])   # contain integer & floating numbers 
print(a.dtype)
print(a[1,1].dtype)
print(a[0].dtype)

print()
a = np.array([[10, 20.3, 30], [10, 10, 'abc']])  # contain integer & floating numbers & strings
print(a.dtype)
print(a[1,1].dtype)
print(a[0].dtype)

[[10 20 30]
 [10 10 40]] 

int32
int32
int32

float64
float64
float64

<U32
<U2
<U32


In [425]:
# elements in one array of pandas.DataFrame can be different data type 
# one column has one data type in pandas.DataFrames

import pandas as pd

a = pd.DataFrame([[10, 20, 30], [10, 10, 40]])
print(a, '\n')
print(a.dtypes)

print()
a = pd.DataFrame([[10, 20.3, 30], [10, 10, 40]])
print(a.dtypes)


print()
a = pd.DataFrame([[10, 20.3, 30], [10, 10, 'abc']])
print(a.dtypes)


    0   1   2
0  10  20  30
1  10  10  40 

0    int64
1    int64
2    int64
dtype: object

0      int64
1    float64
2      int64
dtype: object

0      int64
1    float64
2     object
dtype: object


#### In sum,  you want to improve performance, make the data type of the same field simple or be only numbers

# 2. Series: 1-dimensional arrays in Pandas

- Series is a one-dimensional labeled array, capable of holding any data type 
    - integers, strings, floating point numbers, Python objects, etc. 
- The axis labels are collectively referred to as the index. 

## 2.1 Series creation and index use

In [426]:
# The basic method to create a Series is to call Series( ) method
# The axis labels are collectively referred to as the index.

import pandas as pd
fruits = ["apple", "orange", "pear", "cherry"]
quantities = [15, 33, 45, 55]
s = pd.Series(quantities, index=fruits)
print(s)

apple     15
orange    33
pear      45
cherry    55
dtype: int64


In [427]:
# Create a custom indexed Series object
# With the index argument, you can name your own labels.

s1 = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s2 = pd.Series(np.random.randn(5), index=list("abcde"))

print(s1)
print()
print(s2)

a   -0.331680
b    0.129322
c    0.378039
d   -0.367217
e    0.269520
dtype: float64

a    0.934429
b    0.310383
c   -0.155103
d   -0.192190
e    0.302668
dtype: float64


In [428]:
# If no index argument is specified, the elemets are labeled with their index number. 
# First elemet has index 0, second elemet has index 1 etc.

import pandas as pd

s = pd.Series([12, 29, 72, 4, 8, 10])
print('s:', s, '\n', sep='\n')
print('s.index:', s.index, '\n', sep='\n') 
print('s.values:', s.values, '\n', sep='\n') 

s:
0    12
1    29
2    72
3     4
4     8
5    10
dtype: int64


s.index:
RangeIndex(start=0, stop=6, step=1)


s.values:
[12 29 72  4  8 10]




In [429]:
# Series.index
# Series.values 

import pandas as pd

fruits = ["apple", "orange", "pear", "cherry"]
quantities = [15, 33, 45, 55]
s = pd.Series(quantities, index=fruits)
print('s:', s, '\n', sep='\n')
print('s.index:', s.index, '\n', sep='\n') 
print('s.values:', s.values, '\n', sep='\n') 

s:
apple     15
orange    33
pear      45
cherry    55
dtype: int64


s.index:
Index(['apple', 'orange', 'pear', 'cherry'], dtype='object')


s.values:
[15 33 45 55]




## 2.2 Elements and data types in Series

### Pandas dtype

- object
- int64
- float64
- bool
- datetime64
- timedelta[ns]
- category


#### https://pbpython.com/pandas_dtypes.html

In [430]:
# One-dimensional array (Series), data types can be different
# if data types of elements are the same, the data type of the Series is this type
# if data types of elements are different, the data type of the Series is an object

import pandas as pd
import numpy as np

s1 = pd.Series([1, 10, 15, 44, 1])
print(s1, '\n')


s2 = pd.Series([1,"abc","6",np.nan,44,1])
print(s2)

print()
print(s1.dtype)

0     1
1    10
2    15
3    44
4     1
dtype: int64 

0      1
1    abc
2      6
3    NaN
4     44
5      1
dtype: object

int64


In [431]:
# Use index numbers or labels to retrieve data 

import numpy as np
import pandas as pd

fruits = ["apple", "orange", "pear", "cherry"]
s = pd.Series([15, 33, 45, 55], index=fruits)
print('s["orange"]:', s["orange"], '\n')     
print('s[1]:', s[1], '\n') 


s["orange"]: 33 

s[1]: 33 



In [432]:
# Hint: a[1] vs. a[[1]] are different, if a is a series
# a[1] means: the element wich index 1 in the Serries
# a[[1]] means: a Series comprises an element with index 1

import numpy as np
import pandas as pd

fruits = ["apple", "orange", "pear", "cherry"]
s = pd.Series([15, 33, 45, 55], index=fruits)
print(s)
print()
print('s.dtype:', s.dtype)
print()
print('s["orange"]:', s["orange"], '\n') 
print('type(s["orange"]):', type(s["orange"]), '\n')  
print('s[["orange"]]:', s[["orange"]], '\n')
print('type(s[["orange"]]):', type(s[["orange"]]), '\n') 

apple     15
orange    33
pear      45
cherry    55
dtype: int64

s.dtype: int64

s["orange"]: 33 

type(s["orange"]): <class 'numpy.int64'> 

s[["orange"]]: orange    33
dtype: int64 

type(s[["orange"]]): <class 'pandas.core.series.Series'> 



## 2.3 Properties and methods about basic information 
- Available in Series & DataFrame  
 
 
- shape: display the number of rows (and the number of columns if there are)
    - df.shape
- index: column index
- columns: Column index of DataFrames (Series does not have this method)
- head(n): Returns the data of the first n columns, the default is 5 columns
- info(): Details of DataFrame (Series does not have this method)
- describe(): descriptive statistics of the data (in each column)


- function
    - len(Series or DataFrame object): the number of data 

In [433]:
import numpy as np
import pandas as pd

ar1 = pd.Series(np.random.randint(5, 10, 6), index = list("ABCDEF")) # Generate an array of 6 integers from 5 to 10 (exclusive), index using ABCDEF
print(ar1, '\n')
print('shape:', ar1.shape, '\n')
print('index:', ar1.index, '\n')
print("head():", ar1.head(), '\n', sep = '\n')
print('describe():', ar1.describe(), '\n', sep = '\n')

print('len:', len(ar1))

A    8
B    7
C    5
D    6
E    5
F    7
dtype: int32 

shape: (6,) 

index: Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object') 

head():
A    8
B    7
C    5
D    6
E    5
dtype: int32


describe():
count    6.000000
mean     6.333333
std      1.211060
min      5.000000
25%      5.250000
50%      6.500000
75%      7.000000
max      8.000000
dtype: float64


len: 6


In [434]:
import numpy as np
import pandas as pd

ar1 = pd.Series(np.random.randint(5, 10, 6), index = list("ABCDEF")) # Generate an array of 6 integers from 5 to 10 (exclusive), index using ABCDEF
print(ar1, '\n')
print('shape:', ar1.shape, '\n')
print('index:', ar1.index, '\n')
print("head():", ar1.head(), '\n', sep = '\n')
print('describe():', ar1.describe(), '\n', sep = '\n')

print('len:', len(ar1))

A    9
B    9
C    6
D    8
E    5
F    6
dtype: int32 

shape: (6,) 

index: Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object') 

head():
A    9
B    9
C    6
D    8
E    5
dtype: int32


describe():
count    6.000000
mean     7.166667
std      1.722401
min      5.000000
25%      6.000000
50%      7.000000
75%      8.750000
max      9.000000
dtype: float64


len: 6


## 2.4 Operation of Series

In [435]:
# Operation of 2 Series objects
import pandas as pd

fruits = ["apple", "orange", "pear", "cherry"]
s = pd.Series([15, 33, 45, 55], index=fruits)
p = pd.Series([11, 16, 21, 32], index=fruits)

print('s:', s, '\n', sep='\n')
print('p:', p, '\n', sep='\n')
print('s + 3:', s + 3, '\n', sep='\n')


print('s+p:\n', s + p, '\n', sep='\n')
print('s-p:\n', s - p, '\n', sep='\n')
print('s*p:\n', s * p, '\n', sep='\n')
print('s/p:\n', s / p, '\n', sep='\n')
print("Total=", sum(s + p))

s:
apple     15
orange    33
pear      45
cherry    55
dtype: int64


p:
apple     11
orange    16
pear      21
cherry    32
dtype: int64


s + 3:
apple     18
orange    36
pear      48
cherry    58
dtype: int64


s+p:

apple     26
orange    49
pear      66
cherry    87
dtype: int64


s-p:

apple      4
orange    17
pear      24
cherry    23
dtype: int64


s*p:

apple      165
orange     528
pear       945
cherry    1760
dtype: int64


s/p:

apple     1.363636
orange    2.062500
pear      2.142857
cherry    1.718750
dtype: float64


Total= 228


In [436]:
fruits = ["apple", "orange", "pear", "cherry"]
s = pd.Series([15, 33, 45, 55], index=fruits)
p = pd.Series([11, 16, 21, 32], index=fruits)

print(s[[1, 3]] + [10, 20], '\n')
print(s[['orange', 'cherry']] + 3, '\n')
print(sum(s[1:]), '\n')
print((s[['orange', 'pear']]) ** 2)

orange    43
cherry    75
dtype: int64 

orange    36
cherry    58
dtype: int64 

133 

orange    1089
pear      2025
dtype: int64


# 3. DataFrame: 2-dimensional arrays in Pandas

## 3.1 Features of DataFrames 

- A 2-dimensional labeled data structure with columns of potentially different types. 
- Like a spreadsheet or SQL table, or a dict of Series objects. 
- Along with the data, you can optionally pass index (row labels) and columns (column labels) arguments.



- It is generally the most commonly used pandas object. 
- Like Series, DataFrame accepts many different kinds of input.


- It is better that data in one column is the same data type, otherwise, the data type is 'object'

In [437]:
import pandas as pd
df1 = pd.DataFrame([['a', 90,85,88,92, 1.78], ['b', 80,70,87,60, 1.68], ['c', 100,95,98,90, 1.7]],columns=['label', 'Math', 'Chinese', 'Physics', 'Programming', 'height'], 
    index=['John', 'Tom', 'Richard'])
print(df1)
print()
print(df1.dtypes)    # show the names of all columns, use ".dtypes" to replace ".dtype"
print()
print(df1['label'].dtype)


        label  Math  Chinese  Physics  Programming  height
John        a    90       85       88           92    1.78
Tom         b    80       70       87           60    1.68
Richard     c   100       95       98           90    1.70

label           object
Math             int64
Chinese          int64
Physics          int64
Programming      int64
height         float64
dtype: object

object


In [438]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame([['a', 90,85,88,92, 1.78], ['b', 80,70,87,60, 1.68], ['c', 100,95,98,90, 1.7]],
                   columns=['label', 'Math', 'Chinese', 'Physics', 'Programming', 'height'], 
                    index=['John', 'Tom', 'Richard'])
print('shape:', df1.shape, '\n')
print('index:', df1.index, '\n')
print("head():", df1.head(), '\n', sep = '\n')
print("head():", df1.info(), '\n', sep = '\n')
print('describe():', df1.describe(), '\n', sep = '\n')

print('len(number of row):', len(df1), '\n')
print('df1.dtypes:', df1.dtypes, sep = '\n')

shape: (3, 6) 

index: Index(['John', 'Tom', 'Richard'], dtype='object') 

head():
        label  Math  Chinese  Physics  Programming  height
John        a    90       85       88           92    1.78
Tom         b    80       70       87           60    1.68
Richard     c   100       95       98           90    1.70


<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, John to Richard
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   label        3 non-null      object 
 1   Math         3 non-null      int64  
 2   Chinese      3 non-null      int64  
 3   Physics      3 non-null      int64  
 4   Programming  3 non-null      int64  
 5   height       3 non-null      float64
dtypes: float64(1), int64(4), object(1)
memory usage: 168.0+ bytes
head():
None


describe():
        Math    Chinese    Physics  Programming    height
count    3.0   3.000000   3.000000     3.000000  3.000000
mean    90.0  83.333333  91.0

## 3.2 Establishment of DataFrames

### 2 common methods to create DataFrames

1. From two-dimensional arrays/lists with indexs (row labels) and columns (column labels)
   
2. From dictionaries with arrays/lists of the same number of elements
  

In [439]:
# Method 1: Create a DataFrame from two-dimensional arrays/list and indexs (row labels) and columns (column labels)

import pandas as pd
df1 = pd.DataFrame([[90,85,88,92], [80,70,87,60], [100,95,98,90]], 
    columns=['Math', 'Chinese', 'Physics', 'Programming'], 
    index=['John', 'Tom', 'Richard'])

datas = [[90,85,88,92], [80,70,87,60], [100,95,98,90]]
idx=['John', 'Tom', 'Richard']
cl=['Math', 'Chinese', 'Physics', 'Programming']
df2 = pd.DataFrame(datas, columns=cl, index=idx)

print(df1)
print()
print(df2)

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Richard   100       95       98           90

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Richard   100       95       98           90


In [440]:
# Method 2: Create DataFrames from dictionaries with arrays/lists of the same number of elements

import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df = pd.DataFrame(dists)

print(df)

print()

print(df.info())

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        13 non-null     object
 1   population  13 non-null     in

In [441]:
# After creating the DataFrame from dictionaries, add the index label

import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
         
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df = pd.DataFrame(dists, index=ordinals)
print('df:\n', df)
# df.to_html("Ch9_2_1a.html")

df2 = pd.DataFrame(dists)
df2.index = ordinals
print('\ndf2:', df2, sep='\n')

df:
                            name  population             city
first       Zhongzheng District      159598      Taipei City
second         Banqiao District      551452  New Taipei City
third          Taoyuan District      441287     Taoyuan City
fourth          Beitun District      275207    Taichung City
fifth            Annan District      192327      Tainan City
sixth           Sanmin District      343203   Kaohsiung City
seventh          Da'an District      309835      Taipei City
eigth           Yonghe District      222531  New Taipei City
ninth             Bade District      198473     Taoyuan City
tenth         Qianzhen District      189623   Kaohsiung City
eleventh      Fengshan District      359125   Kaohsiung City
twelvth          Xinyi District      225561      Taipei City
thirteenth     Xindian District      302070  New Taipei City

df2:
                           name  population             city
first       Zhongzheng District      159598      Taipei City
second       

In [442]:
# Add the index label after building the DataFrame

import numpy as np
import pandas as pd

v = np.random.randint(1, 101, (3,4))# Generate a two-dimensional array of 3*4 integers from 5 to 10 (exclusive)

df = pd.DataFrame(v)
print(df)
print()

df.index = list('ABC') # df.index = ('A', 'B', 'C')
df.columns = list('abcd')
print(df)

    0   1   2   3
0  53  57  95  74
1  51  97  38  15
2  64  74  25  85

    a   b   c   d
A  53  57  95  74
B  51  97  38  15
C  64  74  25  85


In [443]:
# When the column (index) and column (row) title is not set, the sequence of 0, 1, 2, ... will be used as the title

import numpy as np
import pandas as pd

v = np.random.randint(1, 101, (3,4))# Generate a two-dimensional array of 3*4 integers from 5 to 10 (exclusive)
df = pd.DataFrame(v)

print(df)

    0   1   2   3
0  21  21  66  98
1  46  65  51  97
2  74   4  37  38


In [444]:
# Row or column headers can be omitted when creating, and can be set or modified later

import pandas as pd
df = pd.DataFrame([[90,85,88,92], [80,70,87,60], [100,95,98,90]])
print(df)
print()

idx=['John', 'Tom', 'Richard']
cl=['Math', 'Chinese', 'Physics', 'Programming']
df.columns=cl
df.index=idx
print(df)
print()

idx[0]='Irene'
df.index=idx
cl[1]='Algorithm'
df.columns=cl
print(df)

     0   1   2   3
0   90  85  88  92
1   80  70  87  60
2  100  95  98  90

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Richard   100       95       98           90

         Math  Algorithm  Physics  Programming
Irene      90         85       88           92
Tom        80         70       87           60
Richard   100         95       98           90


In [445]:
# View basic information of DataFrame

# Save the DataFrame object as HTML and save it to a file
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df = pd.DataFrame(dists)
print(df) # column headers are not aligned with values

print('\nshape:', df.shape)
print('\nindex:', df.index)
print('\ncolumns:', df.columns)
print("\nhead():\n", df.head())
print('\ndescribe():\n', df.describe()) # Display the number, average, standard deviation, maximum, minimum, P25, P50, P75 of each column

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City

shape: (13, 3)

index: RangeIndex(start=0, stop=13, step=1)

columns: Index(['name', 'population', 'city'], dtype='object')

head():
                   name  population             city
0  Zhongzheng District      159598      Taipei City
1     Banqiao Distr

## 3.3 Display DataFrame basic information

- shape: display the number of rows (and the number of columns)
    - df.shape
- index: row labels
- columns: column labels (Series does not have this attributes)
- info(): Details of DataFrame (Series does not have this method)
- describe(): descriptive statistics of the data (in each column)
- dtypes: display the data type of every column
    - Note: Numpy use dtype
- len(Series or DataFrame object): the number of data entries - > is a function, not a method


In [446]:
# View basic information of DataFrame

# Save the DataFrame object as HTML and save it to a file
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df = pd.DataFrame(dists)
print(df) # column headers are not aligned with values

print('\nshape:', df.shape)
print('\nindex:', df.index)
print('\ncolumns:', df.columns)
print('\ndescribe():\n', df.describe()) # Display the number, average, standard deviation, maximum, minimum, P25, P50, P75 of each column

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City

shape: (13, 3)

index: RangeIndex(start=0, stop=13, step=1)

columns: Index(['name', 'population', 'city'], dtype='object')

describe():
           population
count      13.000000
mean   290022.461538
std    113031.540213
min    159598.000000
25%    198473.

- The head(n)
    - displays the first n records, the default is 5 records
- The tail(n)
    - displays the last n records, the default is also 5 records

In [447]:
print(df.head(), '\n') 
print(df.head(3), '\n')
print(df.tail(), '\n')

                  name  population             city
0  Zhongzheng District      159598      Taipei City
1     Banqiao District      551452  New Taipei City
2     Taoyuan District      441287     Taoyuan City
3      Beitun District      275207    Taichung City
4       Annan District      192327      Tainan City 

                  name  population             city
0  Zhongzheng District      159598      Taipei City
1     Banqiao District      551452  New Taipei City
2     Taoyuan District      441287     Taoyuan City 

                 name  population             city
8       Bade District      198473     Taoyuan City
9   Qianzhen District      189623   Kaohsiung City
10  Fengshan District      359125   Kaohsiung City
11     Xinyi District      225561      Taipei City
12   Xindian District      302070  New Taipei City 



## 3.4 Rows, Columns & Index

### Order of columns

In [448]:
# Reassign the column order of DataFrame objects 

import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
         
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]

df1 = pd.DataFrame(dists, index=ordinals)
print('Original:', df1, sep='\n')

df2 = pd.DataFrame(dists,
                  columns = ["name", "city", "population"],
                  index=ordinals)

print('\nReset:', df2, sep='\n')

print()

df3 = pd.DataFrame(dists, index=ordinals)
df3.columns = ["population", "name", "city" ]
print(df3)

Original:
                           name  population             city
first       Zhongzheng District      159598      Taipei City
second         Banqiao District      551452  New Taipei City
third          Taoyuan District      441287     Taoyuan City
fourth          Beitun District      275207    Taichung City
fifth            Annan District      192327      Tainan City
sixth           Sanmin District      343203   Kaohsiung City
seventh          Da'an District      309835      Taipei City
eigth           Yonghe District      222531  New Taipei City
ninth             Bade District      198473     Taoyuan City
tenth         Qianzhen District      189623   Kaohsiung City
eleventh      Fengshan District      359125   Kaohsiung City
twelvth          Xinyi District      225561      Taipei City
thirteenth     Xindian District      302070  New Taipei City

Reset:
                           name             city  population
first       Zhongzheng District      Taipei City      159598
second

### Transpose rows & columns

In [449]:
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
       
df = pd.DataFrame(dists)

print(df)
print()
a = df.T
print('new columns:\n', a.columns)
print('\ndf.T:\n', a)

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City

new columns:
 RangeIndex(start=0, stop=13, step=1)

df.T:
                              0                 1                 2   \
name        Zhongzheng District  Banqiao District  Taoyuan District   
population               159598            551452       

### Index

#### Existed column label as the index

In [450]:
# Use the existing field as the index, there are two ways, whether the field is repeated or not is not the same

import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
                
df = pd.DataFrame(dists, index=dists['city']) 
# The existed city column is retained, and a copy of the city column is used as index
print(df)
print()

df = pd.DataFrame(dists, columns = ['name', 'population'], index=dists['city']) 
# Do not use the existed city column, use the city column as index
print(df)

                                name  population             city
Taipei City      Zhongzheng District      159598      Taipei City
New Taipei City     Banqiao District      551452  New Taipei City
Taoyuan City        Taoyuan District      441287     Taoyuan City
Taichung City        Beitun District      275207    Taichung City
Tainan City           Annan District      192327      Tainan City
Kaohsiung City       Sanmin District      343203   Kaohsiung City
Taipei City           Da'an District      309835      Taipei City
New Taipei City      Yonghe District      222531  New Taipei City
Taoyuan City           Bade District      198473     Taoyuan City
Kaohsiung City     Qianzhen District      189623   Kaohsiung City
Kaohsiung City     Fengshan District      359125   Kaohsiung City
Taipei City           Xinyi District      225561      Taipei City
New Taipei City     Xindian District      302070  New Taipei City

                                name  population
Taipei City      Zhongzhen

In [451]:
# There is no name for the index

import pandas as pd
df = pd.DataFrame([[90,85,88,92], [80,70,87,60], [100,95,98,90], [80,80,80,80]], 
    columns=['Math', 'Chinese', 'Physics', 'Programming'], 
    index=['John', 'Tom', 'Richard', 'Rebecca'])
print(df)

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Richard   100       95       98           90
Rebecca    80       80       80           80


In [452]:
# df.set_index( )
# There is a name for the index 

df2 = df.set_index("Chinese")
print(df2)

         Math  Physics  Programming
Chinese                            
85         90       88           92
70         80       87           60
95        100       98           90
80         80       80           80


In [453]:
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df_dist = pd.DataFrame(dists)

print(df_dist)

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City


In [454]:
# sort by index

df_dist.sort_index(ascending=False, inplace=True)  
print(df_dist)

                   name  population             city
12     Xindian District      302070  New Taipei City
11       Xinyi District      225561      Taipei City
10    Fengshan District      359125   Kaohsiung City
9     Qianzhen District      189623   Kaohsiung City
8         Bade District      198473     Taoyuan City
7       Yonghe District      222531  New Taipei City
6        Da'an District      309835      Taipei City
5       Sanmin District      343203   Kaohsiung City
4        Annan District      192327      Tainan City
3       Beitun District      275207    Taichung City
2      Taoyuan District      441287     Taoyuan City
1      Banqiao District      551452  New Taipei City
0   Zhongzheng District      159598      Taipei City


In [455]:
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df_dist = pd.DataFrame(dists, index = range(13))

print(df_dist)

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City


In [456]:
# Sort by index value
# ascending=True ==> Sort from smallest to largest
# inplace=True   ==> DataFrame itself will be modified

df2 = df_dist.set_index("population")  # 設定排序的參照欄位
print(df2.head())


df3 = df2.sort_index(ascending=False, inplace=False)  
# return a sorted DataFrame, but itself does not change

print('\ninplace=False:\ndf2.head():')
print(df2.head(), '\n')
print('\ndf3.head():')
print(df3.head(), '\n')


df3 = df2.sort_index(ascending=False, inplace=True)  
# return None, but itself changes

print('\ninplace=False:\ndf2.head():')
print(df2.head(), '\n')
print('\ndf3:\n')
print(df3, '\n')

                           name             city
population                                      
159598      Zhongzheng District      Taipei City
551452         Banqiao District  New Taipei City
441287         Taoyuan District     Taoyuan City
275207          Beitun District    Taichung City
192327           Annan District      Tainan City

inplace=False:
df2.head():
                           name             city
population                                      
159598      Zhongzheng District      Taipei City
551452         Banqiao District  New Taipei City
441287         Taoyuan District     Taoyuan City
275207          Beitun District    Taichung City
192327           Annan District      Tainan City 


df3.head():
                         name             city
population                                    
551452       Banqiao District  New Taipei City
441287       Taoyuan District     Taoyuan City
359125      Fengshan District   Kaohsiung City
343203        Sanmin District   Kaoh

# 4. Access elements in DataFrames

## 4.1 From Rows & Columns

1. df.Column_Label
2. df[ ]
3. df.loc[ ]
    - recommended
4. df.iloc[ ]  
    - recommended
3. df.values[ ]
    - recommended

In [457]:
import pandas as pd
df = pd.DataFrame([[90,85,88,92], [80,70,87,60], [100,95,98,90], [80,80,80,80]], 
    columns=['Math', 'Chinese', 'Physics', 'Programming'], 
    index=['John', 'Tom', 'Richard', 'Rebecca'])
print(df)

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Richard   100       95       98           90
Rebecca    80       80       80           80


### Method 1:

#### - df.Column_Label

In [458]:
print(df.Chinese)    # without " "

John       85
Tom        70
Richard    95
Rebecca    80
Name: Chinese, dtype: int64


### Method 2:

#### - df [ ]
- df ['Row_Label']
    - return a Series object
- df [Row_Label List]
    - df [['Row_Label1', 'Row_Label2',...]]
        - return a DataFrame object  
    
    
- df [Column slice]
    - df['Started_Column_Label': 'Ended_Column_Label']_ 
        - return a DataFrame object
    - df[Started_Column_Index: Ended_Column_Label]
        - return a DataFrame object

- df [Column][Row]
    - Combine the above 
    - df[Column Slice][Row_Label List]
    - df[Column_Slice][Row_Index_Value List]

In [459]:
import pandas as pd
df = pd.DataFrame([[90,85,88,92], [80,70,87,60], [100,95,98,90], [80,80,80,80]], 
    columns=['Math', 'Chinese', 'Physics', 'Programming'], 
    index=['John', 'Tom', 'Rebecca', 'Richard'])

v = np.random.randint(1, 101, (6,6))# Generate a two-dimensional array of 3*4 integers from 5 to 10 (exclusive)
df3 = pd.DataFrame(v)



#### df[Row_Label]
#### df[Row_Label List]
    - df[[Row_Name1, Row_Name2,...]]

In [460]:
# df[Row_Name]
# df[[Row_Name1, Row_Name2,...]]

print(df, '\n')
print("df['Math'] ->", df['Math'], sep='\n')
print("\ntype(df['Math']):", type(df['Math']))

print("\ndf[['Math', 'Physics']] ->", df[['Math', 'Physics']], sep='\n')
print("\ntype(df[['Math', 'Physics']]):", type(df[['Math', 'Physics']]))


         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 

df['Math'] ->
John        90
Tom         80
Rebecca    100
Richard     80
Name: Math, dtype: int64

type(df['Math']): <class 'pandas.core.series.Series'>

df[['Math', 'Physics']] ->
         Math  Physics
John       90       88
Tom        80       87
Rebecca   100       98
Richard    80       80

type(df[['Math', 'Physics']]): <class 'pandas.core.frame.DataFrame'>


#### - df [Column slice]
- df['Started_Column_Label': 'Ended_Column_Label']
    
- df[Started_Column_Index: Ended_Column_index]   

In [461]:
# df['Started_Column_Label': 'Ended_Column_Label']
    # exclude Ended_Column
# df[Started_Column_Index: Ended_Column_index]     
    # Note: include Ended_Column

print("\ndf['Tom': 'Richard'] ->", df['Tom': 'Richard'], sep='\n')
print("\ntype(df['Tom': 'Richard']):", type(df['Tom': 'Richard']))

print("\ndf[1: 2] ->", df[1: 2], sep='\n')
print("\ntype([1: 2]):", type(df[1: 2]))

print("\ndf[1:] ->", df[1:], sep='\n')
print("\ntype([1:]):", type(df[1:]))


df['Tom': 'Richard'] ->
         Math  Chinese  Physics  Programming
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80

type(df['Tom': 'Richard']): <class 'pandas.core.frame.DataFrame'>

df[1: 2] ->
     Math  Chinese  Physics  Programming
Tom    80       70       87           60

type([1: 2]): <class 'pandas.core.frame.DataFrame'>

df[1:] ->
         Math  Chinese  Physics  Programming
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80

type([1:]): <class 'pandas.core.frame.DataFrame'>


#### df[Column][Row]

In [462]:
# df[Column][Row]

print("df['Math']['Richard'] ->", df['Math']['Richard'], sep='\n')
print("\ntype(df['Math']['Richard']):", type(df['Math']['Richard']))    # numpy.int64

print("\ndf[['Math', 'Chinese']][1:] ->", df[['Math', 'Chinese']][1:], sep='\n')

print("\ndf[['Math', 'Programming']][1:3] ->", df[['Math', 'Programming']][1:3], sep='\n')   # exclude column 3

print("\ntype(df[['Math', 'Programming']][1:3]) ->", type(df[['Math', 'Programming']][1:3]), sep='\n')

print("\ndf[['Math', 'Programming']]['Tom':'Richard'] ->", df[['Math', 'Programming']]['Tom':'Richard'], sep='\n')   # include column 2

print("\ntype(df[['Math', 'Programming']]['Tom':'Richard']) ->", type(df[['Math', 'Programming']]['Tom':'Richard']), sep='\n')

df['Math']['Richard'] ->
80

type(df['Math']['Richard']): <class 'numpy.int64'>

df[['Math', 'Chinese']][1:] ->
         Math  Chinese
Tom        80       70
Rebecca   100       95
Richard    80       80

df[['Math', 'Programming']][1:3] ->
         Math  Programming
Tom        80           60
Rebecca   100           90

type(df[['Math', 'Programming']][1:3]) ->
<class 'pandas.core.frame.DataFrame'>

df[['Math', 'Programming']]['Tom':'Richard'] ->
         Math  Programming
Tom        80           60
Rebecca   100           90
Richard    80           80

type(df[['Math', 'Programming']]['Tom':'Richard']) ->
<class 'pandas.core.frame.DataFrame'>


In [463]:
print(df[['Math', 'Programming']]['Tom':'Richard'], sep='\n')
print()
print(df[['Math', 'Programming']][1:3], sep='\n')

         Math  Programming
Tom        80           60
Rebecca   100           90
Richard    80           80

         Math  Programming
Tom        80           60
Rebecca   100           90


### Method 3

- df.iloc[Row_Index_Number]
    - return one Series 
    

- df.iloc[Row_Index_Number, Column_Index_Number]
    - return one element


- df.iloc[Row_Index Slice, Column_Index Slice]
    - df.iloc[Started_Row_Index:Ended_Row_Index, Started_Column_Index: Ended_Column_Index]
    - df.iloc[Started_Row_Index:Ended_Row_Index: Step, Started_Column_Index: Ended_Column_Index: Step]
   

- df.iloc[Row_Index List, Column_Index List]
    - df.iloc[[Row_Index, Row_Index,...], [Column_Index, Column_Index,...]]


- df.iloc[Row Boolean Array, Column_Boolean Array]

In [464]:
import pandas as pd
df = pd.DataFrame([[90,85,88,92], [80,70,87,60], [100,95,98,90], [80,80,80,80]], 
    columns=['Math', 'Chinese', 'Physics', 'Programming'], 
    index=['John', 'Tom', 'Rebecca', 'Richard'])

v = np.random.randint(1, 101, (6,6))# Generate a two-dimensional array of 3*4 integers from 5 to 10 (exclusive)
df3 = pd.DataFrame(v)

In [465]:
# df.iloc[Row_Index_Number]
#   return one Series

print(df, '\n')

print(df.iloc[1], '\n')  
print(type(df.iloc[1]), '\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 

Math           80
Chinese        70
Physics        87
Programming    60
Name: Tom, dtype: int64 

<class 'pandas.core.series.Series'> 



In [466]:
# df.iloc[Row_Index Slice]
#   return one Series

print(df, '\n')

print(df.iloc[1:3], '\n')  
print(type(df.iloc[1:3]), '\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 

         Math  Chinese  Physics  Programming
Tom        80       70       87           60
Rebecca   100       95       98           90 

<class 'pandas.core.frame.DataFrame'> 



In [467]:
# df.iloc[Row_Index list]
#   return one Series

print(df, '\n')

print(df.iloc[[0, 1, 3]], '\n')     # double []
print(type(df.iloc[[0, 1, 3]]), '\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Richard    80       80       80           80 

<class 'pandas.core.frame.DataFrame'> 



In [468]:
# df.iloc[Row_Index_Number, Column_Index_Number]
#   return one element

print(df, '\n')

print(df.iloc[1, 3], '\n')  # row the element on the 2nd row, 4th column
print(type(df.iloc[1,3]), '\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 

60 

<class 'numpy.int64'> 



In [469]:
# df.iloc[Row_Index Slice, Column_Index Slice]
#    df.iloc[Started_Row_Index:Ended_Row_Index, Started_Column_Index: Ended_Column_Index]
#    df.iloc[Started_Row_Index:Ended_Row_Index: Step, Started_Column_Index: Ended_Column_Index: Step]

print(df, '\n')

print('\ndf.iloc[1:3,1:]:', df.iloc[1:3,1:], sep='\n')   # exclude raw 3
print('\ntype(df.iloc[1:3,1:]):', type(df.iloc[1:3,1:]))

print('\ndf.iloc[1:3,::2]:', df.iloc[1:3,::2], sep='\n')   # exclude raw 3
print('\ntype(df.iloc[1:3,::2]):', type(df.iloc[1:3,::2]))

print('\ndf.iloc[1:-1,:]:', df.iloc[1:-1,:], sep='\n')   # exclude raw 3
print('\ntype(df.iloc[1:-1,:]):', type(df.iloc[1:-1,:]))

print('\ndf.iloc[1:-1]:', df.iloc[1:-1], sep='\n')   # exclude raw 3
print('\ntype(df.iloc[1:-1]):', type(df.iloc[1:-1]))

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 


df.iloc[1:3,1:]:
         Chinese  Physics  Programming
Tom           70       87           60
Rebecca       95       98           90

type(df.iloc[1:3,1:]): <class 'pandas.core.frame.DataFrame'>

df.iloc[1:3,::2]:
         Math  Physics
Tom        80       87
Rebecca   100       98

type(df.iloc[1:3,::2]): <class 'pandas.core.frame.DataFrame'>

df.iloc[1:-1,:]:
         Math  Chinese  Physics  Programming
Tom        80       70       87           60
Rebecca   100       95       98           90

type(df.iloc[1:-1,:]): <class 'pandas.core.frame.DataFrame'>

df.iloc[1:-1]:
         Math  Chinese  Physics  Programming
Tom        80       70       87           60
Rebecca   100       95       98           90

type(df.iloc[1:-1]): <class 'pandas.core.frame.DataFrame'>

In [470]:
# df.iloc[Row_Index List, Column_Index List]
#   df.iloc[[Row_Index, Row_Index,...], [Column_Index, Column_Index,...]]

print(df, '\n')

print('\ndf.iloc[[1,3],1:]:', df.iloc[[1,3],1:], sep='\n')
print('\ntype(df.ilocc[[1,3],1:]):', type(df.iloc[[1,3],1:]))

print('\ndf.iloc[[1,3],[0, 2]]:', df.iloc[[1,3],[0, 2]], sep='\n')   
print('\ntype(df.iloc[[1,3],[0, 2]]):', type(df.iloc[[1,3],[0, 2]]), sep='\n')

print('\ndf.iloc[[1,3],1::2]:', df.iloc[[1,3],1::2], sep='\n')
print('\ntype(df.iloc[1:3,1::2]):', type(df.iloc[1:3,1::2]))

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 


df.iloc[[1,3],1:]:
         Chinese  Physics  Programming
Tom           70       87           60
Richard       80       80           80

type(df.ilocc[[1,3],1:]): <class 'pandas.core.frame.DataFrame'>

df.iloc[[1,3],[0, 2]]:
         Math  Physics
Tom        80       87
Richard    80       80

type(df.iloc[[1,3],[0, 2]]):
<class 'pandas.core.frame.DataFrame'>

df.iloc[[1,3],1::2]:
         Chinese  Programming
Tom           70           60
Richard       80           80

type(df.iloc[1:3,1::2]): <class 'pandas.core.frame.DataFrame'>


In [471]:
# Hint: a[1] vs. a[[1]] are different, if a is a DataFrame
# a[1] means: the Series wich row index 1 in the Pandas
# a[[1]] means: a Dataframe comprises elements in row index 1

print(df, '\n')

print(df.iloc[1], '\n')  # row the element on the 2nd row, 5th column
print(type(df.iloc[1]), '\n')

print(df.iloc[[1]], '\n')  # row the element on the 2nd row, 5th column
print(type(df.iloc[[1]]), '\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 

Math           80
Chinese        70
Physics        87
Programming    60
Name: Tom, dtype: int64 

<class 'pandas.core.series.Series'> 

     Math  Chinese  Physics  Programming
Tom    80       70       87           60 

<class 'pandas.core.frame.DataFrame'> 



### Method 4

- df.loc[Row_Label]


- df.loc[Row_Label, Column_Label]


- df.loc[Row_Label Slice, Column_Label Slice]
    - df.loc[Started_Row_Label:Ended_Row_Label, Started_Column_Label: Ended_Column_Label]
    - df.loc[Started_Row_Index:Ended_Row_Label: Step, Started_Column_Label: Ended_Column_Label: Step]
   
   
- df.loc[Row_Label List, Column_Label List]
    - df.iloc[[Row_Label, Row_Label,...], [Column_Label, Column_Label,...]]
    
    
- df.loc[Row Boolean Array, Column_Boolean Array]

In [472]:
# df.loc[Row_Label]

print(df, '\n')
print()
print("\ndf.loc['Richard', 'Chinese']:",df.loc['Richard', 'Chinese'], sep='\n')
print("\ntype(df.loc['Richard', 'Chinese']):", type(df.loc['Richard', 'Chinese']), sep='\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 



df.loc['Richard', 'Chinese']:
80

type(df.loc['Richard', 'Chinese']):
<class 'numpy.int64'>


In [473]:
# df.loc[Row_Label, Column_Label]

print(df, '\n')
print()
print("\ndf.loc['Richard']:",df.loc['Richard'], sep='\n')
print("\ntype(df.loc['Richard']):",type(df.loc['Richard']), sep='\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 



df.loc['Richard']:
Math           80
Chinese        80
Physics        80
Programming    80
Name: Richard, dtype: int64

type(df.loc['Richard']):
<class 'pandas.core.series.Series'>


In [474]:
# df.loc[Row_Label Slice, Column_Label Slice]
#   df.loc[Started_Row_Label:Ended_Row_Label, Started_Column_Label: Ended_Column_Label]
#   df.loc[Started_Row_Index:Ended_Row_Label: Step, Started_Column_Label: Ended_Column_Label: Step]


print(df, '\n')

print('\ndf.loc["Tom":,"Chinese":"Programming"]:', df.loc["Tom":,"Chinese":"Programming"], sep='\n')
print('\ntype(df.loc["Tom":,"Chinese":"Programming"]):', type(df.loc["Tom":,"Chinese":"Programming"]))

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 


df.loc["Tom":,"Chinese":"Programming"]:
         Chinese  Physics  Programming
Tom           70       87           60
Rebecca       95       98           90
Richard       80       80           80

type(df.loc["Tom":,"Chinese":"Programming"]): <class 'pandas.core.frame.DataFrame'>


In [475]:
# df.loc[Row_Label List, Column_Label List]
#    df.iloc[[Row_Label, Row_Label,...], [Column_Label, Column_Label,...]]

print(df, '\n')

print('\ndf.loc[["Tom","Richard"],:"Physics"]:', df.loc[["Tom","Richard"],:"Physics"], sep='\n')
# include "Physics column"
print('\ntype(df.loc[["Tom","Richard"],:"Physics"]):', type(df.loc[["Tom","Richard"],:"Physics"]), sep='\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 


df.loc[["Tom","Richard"],:"Physics"]:
         Math  Chinese  Physics
Tom        80       70       87
Richard    80       80       80

type(df.loc[["Tom","Richard"],:"Physics"]):
<class 'pandas.core.frame.DataFrame'>


### Method 5: only retrieve data

- df.values

- df.values[Row_Index]
- df.values[Row_Index Slice]
    - df.values[Started_Row_Index: Ended_Row_Index]
    - df.values[Started_Row_Index: Ended_Row_Index: Step]

- df.values[Row_Index, Column_Index]
- df.values[Row_Index Slice, Column_Index Slice]
    - df.values[Started_Row_Index:Ended_Row_Index, Started_Column_Index: Ended_Column_Index]
    - df.values[Started_Row_Index:Ended_Row_Index: Step, Started_Column_Index: Ended_Column_Index: Step]

In [476]:
import pandas as pd
df = pd.DataFrame([[90,85,88,92], [80,70,87,60], [100,95,98,90], [80,80,80,80]], 
    columns=['Math', 'Chinese', 'Physics', 'Programming'], 
    index=['John', 'Tom', 'Rebecca', 'Richard'])

v = np.random.randint(1, 101, (6,6))# Generate a two-dimensional array of 3*4 integers from 5 to 10 (exclusive)
df3 = pd.DataFrame(v)



#### - df.values
    - Whole data in the DataFrame

#### - df.values[Row_Index]
#### - df.values[Row_Indexm Slice]
- df.values[Started_Row_Index: Ended_Row_Index]
- df.values[Started_Row_Index: Ended_Row_Index: Step]

In [477]:
# df.values[Row]

print(df3, '\n')
print('\ndf3.values:', df3.values, sep='\n')
print('\ntype(df3.values):',type(df3.values))

print('df3.values[1]:', df3.values[1], sep='\n')
print('\ntype(df3.values[1]):', type(df3.values[1]))

print('\ndf3.values[1:3]:', df3.values[1:3], sep='\n')     # exclude row index 3
print('\ntype(df3.values[1:3]):', type(df3.values[1:3]))   

print('\ndf3.values[1::2]:', df3.values[1::2], sep='\n')
print('\ntype(df3.values[1::2]):', type(df3.values[1::2]))

    0   1   2   3   4    5
0  53  88  87  55  59   91
1   2  15  25  38  66   24
2  62  82  81  12  59  100
3  73  71  37  38  88   87
4  70  15  77  87  71   21
5  86  33  99  28  75   43 


df3.values:
[[ 53  88  87  55  59  91]
 [  2  15  25  38  66  24]
 [ 62  82  81  12  59 100]
 [ 73  71  37  38  88  87]
 [ 70  15  77  87  71  21]
 [ 86  33  99  28  75  43]]

type(df3.values): <class 'numpy.ndarray'>
df3.values[1]:
[ 2 15 25 38 66 24]

type(df3.values[1]): <class 'numpy.ndarray'>

df3.values[1:3]:
[[  2  15  25  38  66  24]
 [ 62  82  81  12  59 100]]

type(df3.values[1:3]): <class 'numpy.ndarray'>

df3.values[1::2]:
[[ 2 15 25 38 66 24]
 [73 71 37 38 88 87]
 [86 33 99 28 75 43]]

type(df3.values[1::2]): <class 'numpy.ndarray'>


In [478]:
print(df, '\n')
print('\ndf.values:', df.values, sep='\n')
print('\ntype(df.values):',type(df.values))

print('df.values[1]:', df.values[1], sep='\n')
print('\ntype(df.values[1]):', type(df.values[1]))

print('\ndf.values[1:3]:', df.values[1:3], sep='\n')
print('\ntype(df.values[1:3]):', type(df.values[1:3]))

print('\ndf.values[1::2]:', df.values[1::2], sep='\n')
print('\ntype(df.values[1::2]):', type(df.values[1::2]))

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 


df.values:
[[ 90  85  88  92]
 [ 80  70  87  60]
 [100  95  98  90]
 [ 80  80  80  80]]

type(df.values): <class 'numpy.ndarray'>
df.values[1]:
[80 70 87 60]

type(df.values[1]): <class 'numpy.ndarray'>

df.values[1:3]:
[[ 80  70  87  60]
 [100  95  98  90]]

type(df.values[1:3]): <class 'numpy.ndarray'>

df.values[1::2]:
[[80 70 87 60]
 [80 80 80 80]]

type(df.values[1::2]): <class 'numpy.ndarray'>


#### - df.values[Row_Index, Column_Index]
#### - df.values[Row_Index Slice, Column_Index Slice]

In [479]:
print(df3, '\n')

print('\ndf3.values[1,2]:',df3.values[1,2], sep='\n')
print('\ntype(df3.values[1,2]):', type(df3.values[1,2]))

print('\ndf3.values[1:3,1:]:', df3.values[1:3,1:], sep='\n')
print('\ntype(df3.values[1:3,1:]):', type(df3.values[1:3,1:]))

    0   1   2   3   4    5
0  53  88  87  55  59   91
1   2  15  25  38  66   24
2  62  82  81  12  59  100
3  73  71  37  38  88   87
4  70  15  77  87  71   21
5  86  33  99  28  75   43 


df3.values[1,2]:
25

type(df3.values[1,2]): <class 'numpy.int32'>

df3.values[1:3,1:]:
[[ 15  25  38  66  24]
 [ 82  81  12  59 100]]

type(df3.values[1:3,1:]): <class 'numpy.ndarray'>


In [480]:
print(df, '\n')

print('\ndf.values[1,2]:',df.values[1,2], sep='\n')
print('\ntype(df.values[1,2]):', type(df.values[1,2]))

print('\ndf.values[1:3,1:]:', df.values[1:3,1:], sep='\n')
print('\ntype(df.values[1:3,1:]):', type(df.values[1:3,1:]))

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 


df.values[1,2]:
87

type(df.values[1,2]): <class 'numpy.int64'>

df.values[1:3,1:]:
[[70 87 60]
 [95 98 90]]

type(df.values[1:3,1:]): <class 'numpy.ndarray'>


### special cases

In [481]:
print(df, '\n')
print('\ndf.values[1:3,[3,1]]:', df.values[:,[3,1]], sep='\n')
print('\ndf.values[[1,3],[3,1]]:', df.values[[1,3],[1,2]], sep='\n')

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 


df.values[1:3,[3,1]]:
[[92 85]
 [60 70]
 [90 95]
 [80 80]]

df.values[[1,3],[3,1]]:
[70 80]


## 4.2 From boolean statement

### - Filter data - use boolean statement to filter data

- print(df[df.population > 350000])
- print(df[df["city"].isin(["Taipei","Kaohsiung"])])

In [482]:
import pandas as pd
df = pd.DataFrame([[90,85,88,92], [80,70,87,60], [100,95,98,90], [80,80,80,80]], 
    columns=['Math', 'Chinese', 'Physics', 'Programming'], 
    index=['John', 'Tom', 'Rebecca', 'Richard'])

In [483]:
print(df, '\n')

print(df[df.Math > 80])

print()
print(df[df.Math > 80].loc[:,'Chinese':'Programming'])   # get some columns from new DataFrame

         Math  Chinese  Physics  Programming
John       90       85       88           92
Tom        80       70       87           60
Rebecca   100       95       98           90
Richard    80       80       80           80 

         Math  Chinese  Physics  Programming
John       90       85       88           92
Rebecca   100       95       98           90

         Chinese  Physics  Programming
John          85       88           92
Rebecca       95       98           90


In [484]:
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df_dist = pd.DataFrame(dists)

print(df_dist)

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City


In [485]:
print(df_dist[df_dist.population > 350000], '\n')

print(df_dist[df_dist["city"].isin(["Taipei City","Kaohsiung City"])])

                 name  population             city
1    Banqiao District      551452  New Taipei City
2    Taoyuan District      441287     Taoyuan City
10  Fengshan District      359125   Kaohsiung City 

                   name  population            city
0   Zhongzheng District      159598     Taipei City
5       Sanmin District      343203  Kaohsiung City
6        Da'an District      309835     Taipei City
9     Qianzhen District      189623  Kaohsiung City
10    Fengshan District      359125  Kaohsiung City
11       Xinyi District      225561     Taipei City


In [486]:
print(df_dist[(df_dist.population > 350000) & (df_dist.population < 500000)], '\n')

print(df_dist[df_dist["city"].str.startswith("Taipei")])


                 name  population            city
2    Taoyuan District      441287    Taoyuan City
10  Fengshan District      359125  Kaohsiung City 

                   name  population         city
0   Zhongzheng District      159598  Taipei City
6        Da'an District      309835  Taipei City
11       Xinyi District      225561  Taipei City


# 5. Visit DataFrame

In [487]:
for index, row in df_dist.iterrows() :
    print(index, row["city"], row["name"], row["population"])

0 Taipei City Zhongzheng District 159598
1 New Taipei City Banqiao District 551452
2 Taoyuan City Taoyuan District 441287
3 Taichung City Beitun District 275207
4 Tainan City Annan District 192327
5 Kaohsiung City Sanmin District 343203
6 Taipei City Da'an District 309835
7 New Taipei City Yonghe District 222531
8 Taoyuan City Bade District 198473
9 Kaohsiung City Qianzhen District 189623
10 Kaohsiung City Fengshan District 359125
11 Taipei City Xinyi District 225561
12 New Taipei City Xindian District 302070


# 6. Update, merge and delete DataFrame elements

## 6.1 Update data

In [488]:
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df_dist = pd.DataFrame(dists)

df_dist.to_csv('dists.csv')

In [489]:
# Use the label and location to select the data, you can update the selected data

import pandas as pd

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

print(df.head(2))
# Get and update a single scalar value
print(df.loc[ordinals[0], "population"])
df.loc[ordinals[0], "population"] = 160000
print(df.iloc[1,2])
df.iloc[1,2] = 560000
print(df.head(2))

        Unnamed: 0                 name  population             city
first            0  Zhongzheng District      159598      Taipei City
second           1     Banqiao District      551452  New Taipei City
159598
551452
        Unnamed: 0                 name  population             city
first            0  Zhongzheng District      160000      Taipei City
second           1     Banqiao District      560000  New Taipei City


In [490]:
# Select the record to replace to replace

import pandas as pd
df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

print(df.head(3))
# Get and update a single record
print(df.loc[ordinals[1]])
s = ["top", "New Taipei City", "Xinzhuang District", 416640]
df.loc[ordinals[1]] = s
print(df.head(3))

        Unnamed: 0                 name  population             city
first            0  Zhongzheng District      159598      Taipei City
second           1     Banqiao District      551452  New Taipei City
third            2     Taoyuan District      441287     Taoyuan City
Unnamed: 0                   1
name          Banqiao District
population              551452
city           New Taipei City
Name: second, dtype: object
       Unnamed: 0                 name          population          city
first           0  Zhongzheng District              159598   Taipei City
second        top      New Taipei City  Xinzhuang District        416640
third           2     Taoyuan District              441287  Taoyuan City


In [491]:
# update the entire field value

import pandas as pd
import numpy as np

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

print(df)
# Get and update the entire field
print(df.loc[:, "population"])
df.loc[:, "population"] = np.random.randint(34000, 700000, size=len(df))
print(df.head())

            Unnamed: 0                 name  population             city
first                0  Zhongzheng District      159598      Taipei City
second               1     Banqiao District      551452  New Taipei City
third                2     Taoyuan District      441287     Taoyuan City
fourth               3      Beitun District      275207    Taichung City
fifth                4       Annan District      192327      Tainan City
sixth                5      Sanmin District      343203   Kaohsiung City
seventh              6       Da'an District      309835      Taipei City
eigth                7      Yonghe District      222531  New Taipei City
ninth                8        Bade District      198473     Taoyuan City
tenth                9    Qianzhen District      189623   Kaohsiung City
eleventh            10    Fengshan District      359125   Kaohsiung City
twelvth             11       Xinyi District      225561      Taipei City
thirteenth          12     Xindian District      30

## 6.2 Delete data

- Pandas uses drop to delete DataFrame data, the syntax is:

- df.drop(row or column title [, axis = row and column value])
 - A row and column value of 0 means the column header is sorted (default), and 1 is a row

In [492]:
# Update the entire DataFrame object

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(5, 1500, size=(2,3)))
print(df)

print()
# Get and update the entire DataFrame
print(df[df > 800])

print()
df[df > 800] = df - 100
print(df)

      0    1    2
0  1373  373  258
1   550  977  933

        0      1      2
0  1373.0    NaN    NaN
1     NaN  977.0  933.0

      0    1    2
0  1273  373  258
1   550  877  833


In [493]:
# delete data - delete scalar value

import pandas as pd

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

print(df.head(3))
# delete scalar value
print(df.loc[ordinals[0], "population"])
df.loc[ordinals[0], "population"] = None
print(df.iloc[1,2])
df.iloc[1,2] = None
print(df.head(3))

        Unnamed: 0                 name  population             city
first            0  Zhongzheng District      159598      Taipei City
second           1     Banqiao District      551452  New Taipei City
third            2     Taoyuan District      441287     Taoyuan City
159598
551452.0
        Unnamed: 0                 name  population             city
first            0  Zhongzheng District         NaN      Taipei City
second           1     Banqiao District         NaN  New Taipei City
third            2     Taoyuan District    441287.0     Taoyuan City


In [494]:
# drop() function to delete records

import pandas as pd

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

print(df.head())
# Delete Record
df2 = df.drop(["second", "fourth"]) # 2,4 strokes
print(df2.head())

df.drop(df.index[[2,3]], inplace=True) # 3,4 strokes
print(df.head())

        Unnamed: 0                 name  population             city
first            0  Zhongzheng District      159598      Taipei City
second           1     Banqiao District      551452  New Taipei City
third            2     Taoyuan District      441287     Taoyuan City
fourth           3      Beitun District      275207    Taichung City
fifth            4       Annan District      192327      Tainan City
         Unnamed: 0                 name  population            city
first             0  Zhongzheng District      159598     Taipei City
third             2     Taoyuan District      441287    Taoyuan City
fifth             4       Annan District      192327     Tainan City
sixth             5      Sanmin District      343203  Kaohsiung City
seventh           6       Da'an District      309835     Taipei City
         Unnamed: 0                 name  population             city
first             0  Zhongzheng District      159598      Taipei City
second            1     Banqiao 

In [495]:
# Delete column: also use the drop() function, but you need to specify that the axis parameter value is 1, and the default is 0, which is to delete the record (column)

import pandas as pd

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

print(df.head(3))
# delete field
df2 = df.drop(["population"], axis=1)
print(df2.head(3))

        Unnamed: 0                 name  population             city
first            0  Zhongzheng District      159598      Taipei City
second           1     Banqiao District      551452  New Taipei City
third            2     Taoyuan District      441287     Taoyuan City
        Unnamed: 0                 name             city
first            0  Zhongzheng District      Taipei City
second           1     Banqiao District  New Taipei City
third            2     Taoyuan District     Taoyuan City


## 6.3 Add data

In [496]:
# To add a record, you only need to specify a non-existing index label to add a record. We can also create a Series object, and then use the append() function to add a record

import pandas as pd

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

print(df.tail(3))
# add record
print()
df.loc["third-1"] = ['New', "Taipei City", "Shilin District", 288340]
print(df.tail(3))

s = pd.Series({"city":"New Taipei City","name":"Zhonghe District","population":413291})
df2 = df.append(s, ignore_index=True)
print('\n', df2.tail(3))

            Unnamed: 0               name  population             city
eleventh            10  Fengshan District      359125   Kaohsiung City
twelvth             11     Xinyi District      225561      Taipei City
thirteenth          12   Xindian District      302070  New Taipei City

           Unnamed: 0              name       population             city
twelvth            11    Xinyi District           225561      Taipei City
thirteenth         12  Xindian District           302070  New Taipei City
third-1           New       Taipei City  Shilin District           288340

    Unnamed: 0              name       population             city
12         12  Xindian District           302070  New Taipei City
13        New       Taipei City  Shilin District           288340
14        NaN  Zhonghe District           413291  New Taipei City


In [497]:
# Use the new record to create a DataFrame object with the for/in loop, first use the loc indexer
# Use the append() function to add a Series object to create a DataFrame object
import pandas as pd

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

print(df.tail(3))
# add record
df.loc["last"] = ["last", "Taipei City", "Shilin District", 288340]
print()
print(df.tail(3))

s = pd.Series({"city":"New Taipei City","name":"Zhonghe District","population":413291})
df2 = df.append(s, ignore_index=True)
print()
print(df2.tail(3))

            Unnamed: 0               name  population             city
eleventh            10  Fengshan District      359125   Kaohsiung City
twelvth             11     Xinyi District      225561      Taipei City
thirteenth          12   Xindian District      302070  New Taipei City

           Unnamed: 0              name       population             city
twelvth            11    Xinyi District           225561      Taipei City
thirteenth         12  Xindian District           302070  New Taipei City
last             last       Taipei City  Shilin District           288340

   Unnamed: 0              name       population             city
12         12  Xindian District           302070  New Taipei City
13       last       Taipei City  Shilin District           288340
14        NaN  Zhonghe District           413291  New Taipei City


In [498]:
# Add: Specify a non-existing field label to add a field. We can use a list, a Series object or a NumPy array to specify the field value

import pandas as pd
from numpy.random import randint

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

df["area"] = pd.Series([randint(6000,9000) for n in range(len(df))]).values
print(df.head())
df.head().to_html("Ch9_4_3b_01.html")
df.loc[:,"zip"] = randint(100, 120, size=len(df))
print(df.head())
df.head().to_html("Ch9_4_3b_02.html")

        Unnamed: 0                 name  population             city  area
first            0  Zhongzheng District      159598      Taipei City  8531
second           1     Banqiao District      551452  New Taipei City  6991
third            2     Taoyuan District      441287     Taoyuan City  7047
fourth           3      Beitun District      275207    Taichung City  6779
fifth            4       Annan District      192327      Tainan City  8277
        Unnamed: 0                 name  population             city  area  \
first            0  Zhongzheng District      159598      Taipei City  8531   
second           1     Banqiao District      551452  New Taipei City  6991   
third            2     Taoyuan District      441287     Taoyuan City  7047   
fourth           3      Beitun District      275207    Taichung City  6779   
fifth            4       Annan District      192327      Tainan City  8277   

        zip  
first   106  
second  105  
third   113  
fourth  106  
fifth   103

## 6.4 Duplicate, concatenate and merge data 

### - Create empty and duplicate DataFrame objects

*For an existing DataFrame object, we can create an empty DataFrame object with the same shape but no data, or we can use the copy() function to back up the DataFrame object before processing, as follows:* columns =["city","name", "population"]
    *df_empty = pd.DataFrame(np.nan, index=ordinals, columns=columns)* print(df_empty)

* The copy() function can copy DataFrame objects as follows:
    * df_copy = df.copy()
    * print(df_copy)

In [499]:
import pandas as pd
import numpy as np

df = pd.read_csv("dists.csv", encoding="utf8")
ordinals =["first", "second", "third", "fourth", "fifth",
           "sixth", "seventh", "eigth", "ninth", "tenth",
           "eleventh", "twelvth", "thirteenth"]
df.index = ordinals

columns =["city","name", "population"]
# Create empty DataFrame object
df_empty = pd.DataFrame(np.nan, index=ordinals, columns=columns)
print(df_empty)
# Copy the DataFrame object
df_copy = df.copy()
print(df_copy)

            city  name  population
first        NaN   NaN         NaN
second       NaN   NaN         NaN
third        NaN   NaN         NaN
fourth       NaN   NaN         NaN
fifth        NaN   NaN         NaN
sixth        NaN   NaN         NaN
seventh      NaN   NaN         NaN
eigth        NaN   NaN         NaN
ninth        NaN   NaN         NaN
tenth        NaN   NaN         NaN
eleventh     NaN   NaN         NaN
twelvth      NaN   NaN         NaN
thirteenth   NaN   NaN         NaN
            Unnamed: 0                 name  population             city
first                0  Zhongzheng District      159598      Taipei City
second               1     Banqiao District      551452  New Taipei City
third                2     Taoyuan District      441287     Taoyuan City
fourth               3      Beitun District      275207    Taichung City
fifth                4       Annan District      192327      Tainan City
sixth                5      Sanmin District      343203   Kaohsiung City

In [500]:
# Connect multiple DataFrame objects: Use the concat() function to connect multiple DataFrame objects, and the number of data entries increases

import pandas as pd
from numpy.random import randint

df1 = pd.DataFrame(randint(5,10,size=(3,4)),columns=["a","b","c","d"])
df2 = pd.DataFrame(randint(5,10,size=(2,3)),columns=["b","d","a"])
print(df1)

print()
print(df2)

print()
df3 = pd.concat([df1,df2])
print(df3)
print()

df4 = pd.concat([df1,df2], ignore_index=True) # ignore index labels
print(df4)

   a  b  c  d
0  7  9  8  7
1  7  5  5  9
2  8  6  8  6

   b  d  a
0  8  8  8
1  9  5  6

   a  b    c  d
0  7  9  8.0  7
1  7  5  5.0  9
2  8  6  8.0  6
0  8  8  NaN  8
1  6  9  NaN  5

   a  b    c  d
0  7  9  8.0  7
1  7  5  5.0  9
2  8  6  8.0  6
3  8  8  NaN  8
4  6  9  NaN  5


In [501]:
# Merge 2 DataFrame objects: The merge() function can merge 2 DataFrame objects left and right (similar to SQL merge query), and the data field is increased

import pandas as pd

df1 = pd.DataFrame({"key":["a","b","b"],"data1":range(3)})
df2 = pd.DataFrame({"key":["a","b","c"],"data2":range(3)})
print(df1)
print(df2)


df3 = pd.merge(df1, df2)
print(df3)


df4 = pd.merge(df2, df1)
print(df4)


df5 = pd.merge(df2, df1, how='left')
print(df5)

  key  data1
0   a      0
1   b      1
2   b      2
  key  data2
0   a      0
1   b      1
2   c      2
  key  data1  data2
0   a      0      0
1   b      1      1
2   b      2      1
  key  data2  data1
0   a      0      0
1   b      1      1
2   b      1      2
  key  data2  data1
0   a      0    0.0
1   b      1    1.0
2   b      1    2.0
3   c      2    NaN


# 7. Access files

#### Pandas commonly used methods for importing data:

- read_csv
    - Import a file in CSV format:
- read_excel
- read_sql
- read_json
- read_html 
    - #Need to install html5lib to import HTML files, Pandas will extract the data of the <table> 

### Export DataFrame object to file

* Export to CSV file: pd.to_csv(filename)
* Export to JSON format file: pd.to_json(filename)
* Export as HTML table tag file: pd.to_html(filename)
* Export to Excel file: pd.to_excel(filename)

In [502]:
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df = pd.DataFrame(dists)

df.to_csv("dists.csv", index=False, encoding="utf8")
df.to_json("dists.json")

In [503]:
import pandas as pd

# Import a file in CSV format
df = pd.read_csv("dists.csv", encoding="utf8")
print(df)
df.to_html("test1.html")
# Import a file in JSON format
df2 = pd.read_json("dists.json")
print(df2)
df.to_html("test2.html")

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City
                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichun

In [504]:
import pandas as pd

# Import a file in CSV format
df = pd.read_csv("dists.csv", encoding="utf8", header=0)
print(df)

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City


In [505]:
import pandas as pd

# Import a file in CSV format
df = pd.read_csv("dists.csv", encoding="utf8")
print(df)

                   name  population             city
0   Zhongzheng District      159598      Taipei City
1      Banqiao District      551452  New Taipei City
2      Taoyuan District      441287     Taoyuan City
3       Beitun District      275207    Taichung City
4        Annan District      192327      Tainan City
5       Sanmin District      343203   Kaohsiung City
6        Da'an District      309835      Taipei City
7       Yonghe District      222531  New Taipei City
8         Bade District      198473     Taoyuan City
9     Qianzhen District      189623   Kaohsiung City
10    Fengshan District      359125   Kaohsiung City
11       Xinyi District      225561      Taipei City
12     Xindian District      302070  New Taipei City


In [506]:
# dists.csv

city,name,population
Taipei City, Zhongzheng District, 159598
New Taipei City, Banqiao District, 551452
Taoyuan City, Taoyuan District, 441287
Taichung City, Beitun District, 275207
Tainan City, Annan District, 192327
Kaohsiung City, Sanmin District, 343203
Taipei City, Daan District, 309835
New Taipei City, Yonghe District, 222531
Taoyuan City, Bade District, 198473
Kaohsiung City, Qianzhen District, 189623
Kaohsiung City, Fengshan District, 359125
Taipei City, Xinyi District, 225561
New Taipei City, Xindian District, 302070

SyntaxError: invalid syntax (<ipython-input-506-e1a51829c45f>, line 4)

In [ ]:
#dists.json

{"city":{"0":"\u53f0\u5317\u5e02","1":"\u65b0\u5317\u5e02","2":"\u6843\u5712\u5e02","3":"\u53f0\u4e2d\u5e02","4":"\u53f0\u5357\u5e02","5":"\u9ad8\u96c4\u5e02","6":"\u53f0\u5317\u5e02","7":"\u65b0\u5317\u5e02","8":"\u6843\u5712\u5e02","9":"\u9ad8\u96c4\u5e02","10":"\u9ad8\u96c4\u5e02","11":"\u53f0\u5317\u5e02","12":"\u65b0\u5317\u5e02"},"name":{"0":"\u4e2d\u6b63\u5340","1":"\u677f\u6a4b\u5340","2":"\u6843\u5712\u5340","3":"\u5317\u5c6f\u5340","4":"\u5b89\u5357\u5340","5":"\u4e09\u6c11\u5340","6":"\u5927\u5b89\u5340","7":"\u6c38\u548c\u5340","8":"\u516b\u5fb7\u5340","9":"\u524d\u93ae\u5340","10":"\u9cf3\u5c71\u5340","11":"\u4fe1\u7fa9\u5340","12":"\u65b0\u5e97\u5340"},"population":{"0":159598,"1":551452,"2":441287,"3":275207,"4":192327,"5":343203,"6":309835,"7":222531,"8":198473,"9":189623,"10":359125,"11":225561,"12":302070}}

In [ ]:
# chap. 11

import pandas as pd
tables = pd.read_html("http://www.stockq.org/market/commodity.php")
n = 1
for table in tables:
    print("The "  + " table " + str(n) + ":")
    print(table.head())
    print()
    n += 1

In [ ]:
import pandas as pd
tables = pd.read_html("http://www.stockq.org/market/commodity.php")
table = tables[7]
table = table.drop(table.index[[0,1]])
table.columns = ["commodity", "buy price", "up or down", "proportion", "Taipei"]
table.index = range(len(table.index))
print(table)

### DataFrame save as HTML file

In [ ]:
# Set up the DataFrame object
# Save the DataFrame object as HTML and save it to a file
import pandas as pd

dists = {"name": ["Zhongzheng District", "Banqiao District", "Taoyuan District", "Beitun District",
                   "Annan District", "Sanmin District", "Da'an District", "Yonghe District",
                   "Bade District", "Qianzhen District", "Fengshan District",
                   "Xinyi District", "Xindian District"],
         "population": [159598, 551452, 441287, 275207,
                        192327, 343203, 309835, 222531,
                        198473, 189623, 359125,
                        225561, 302070],
         "city": ["Taipei City", "New Taipei City", "Taoyuan City", "Taichung City",
                  "Tainan City", "Kaohsiung City", "Taipei City", "New Taipei City",
                  "Taoyuan City", "Kaohsiung City", "Kaohsiung City",
                  "Taipei City", "New Taipei City"]}
df = pd.DataFrame(dists)
print(df) # The column title is not aligned with the value, the HTML file of the book debut will be neater
# df.to_html("text\section.html") # Save the DataFrame object as HTML and save it to a file

print('\nshape:', df.shape)
print('\nindex:', df.index)
print('\ncolumns:', df.columns)
print("\nhead():\n", df.head())
print('\ndescribe():\n', df.describe())

In [ ]:
### HTML generated by the above program df.to_html("text\section.html")
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>city</th>
      <th>name</th>
      <th>population</th>
    </tr>
  </thead>
  <tbody>
    <tr>
       <th>0</th>
      <td>Taipei City</td>
      <td>Zhongzheng District</td>
      <td>159598</td>
    </tr>
    <tr>
      <th>1</th>
      <td>New Taipei City</td>
      <td>Itabashi District</td>
      <td>551452</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Taoyuan City</td>
      <td>Taoyuan District</td>
      <td>441287</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Taichung City</td>
      <td>Beitun District</td>
      <td>275207</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Tainan City</td>
      <td>Other District</td>
      <td>192327</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Kaohsiung City</td>
      <td>Sanmin District</td>
      <td>343203</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Taipei City</td>
      <td>Da'an District</td>
      <td>309835</td>
    </tr>
    <tr>
      <th>7</th>
      <td>New Taipei City</td>
      <td>Yonghe District</td>
      <td>222531</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Taoyuan City</td>
      <td>Bade District</td>
      <td>198473</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Kaohsiung City</td>
      <td>Former village</td>
      <td>189623</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Kaohsiung City</td>
      <td>Fengshan District</td>
      <td>359125</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Taipei City</td>
      <td>Xinyi District</td>
      <td>225561</td>
    </tr>
    <tr>
      <th>12</th>
      <td>New Taipei City</td>
      <td>New shopping area</td>
      <td>302070 </td>
    </tr>
  </tbody>
</table>

bibliography:

- Chen Yunjie (2018). Python data science and artificial intelligence application practice. Taipei: Flag.
- W3Schools
- JavaPoints
- Pandas official website