## 目錄
製作者：楊右宇

建立日期：2021.11.13  &emsp; 最後修改日期: 2021.11.13

1. Numpy 簡介  
 1.1 特色  
 1.2 核心與結構  
 1.3 為什麼需要使用 Numpy  
 1.4 顯示函式的說明文件  
 1.5 official website  
2. 基本架構的屬性 (Basic properties)  
 2.1 基本屬性  
 2.2 容易搞混的陣列形狀  
3. 陣列的建立  
 3.1 建立一維陣列常見的方式  
 3.2 建立多維陣列常見的方式  
4. 走訪陣列
5. 取出子陣列
6. 改變陣列的形狀
7. 陣列的運算
8. Numpy的亂數
9. NumPy的通用函式
10. 檔案儲存與載入
11. Numpy陣列的記憶體位置
12. 多項式
 

# Numpy 簡介
## 特色
* NumPy 提供一維、二維、和多維的陣列物件，與相關延伸的物件
* 支援高效率陣列的數學、邏輯、維度操作、排序、選取元素，和基本線性代數與統計等多種數學函式的函式庫

## 核心與結構

* NumPy 的核心是ndarray，是相同資料型態元素所組成的陣列
* 與Python的清單List之差異為： 
    * 資料結構和C語言一樣，為元素數目固定，且所屬的元素都是同一種資料型別 (python的list允許不同的資料型別，且元素數目可以變動)  
    * NumPy陣列是固定尺寸，若是更改物件尺寸就是重新建立全新的陣列，Python的List是容器，不用指定尺寸


## 為什麼需要使用 Numpy

- 支援多維陣列與矩陣運算，針對陣列提供大量的數學函式，方便處理數學問題，例如傅立葉轉換、線性代數、多項式等
- 運算速度快:numpy和pandas 都是採用C 語言編寫, pandas 又是基於numpy, 是numpy的升級版，且採用的是矩陣運算，會比python 自帶的字典或者列表快好多
- 消耗資源少

## 匯入 numpy

In [1]:
# impoort numpy
import numpy as np

## 查詢當前版本

In [2]:
# show numpy version
np.__version__

'1.20.1'

## 顯示函式的說明文件

* numpy.函式名稱?

In [3]:
# show function description
np.sin?

## official website
http://www.numpy.org/

# 基本架構的屬性 (Basic properties)

## 基本屬性

* NumPy套件所提供的陣列型別稱為 ndarray (n-dimension array)  
* ndarray型別的重要屬性：   
 * ndarray.ndim:陣列的維度  
 * ndarray.shape:陣列的形狀(用tuple表示)，每個整數表示各維度的元素個數  
 * ndarray.size:元素的個數  
 * ndarray.dtype:元素的資料型別，包含python內建的int, bool, str等，註：type()是看整個物件的資料型別  
     也可以是NumPy套件提供的numpy.int32, numpy.int16, numpy.float64等  
 * ndarray.itemsize:陣列元素的位元組數  

In [4]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])  
print(array, '\n')
print('維度 :',array.ndim) 
print('各維度元素數 :',array.shape) # 列與行數
print('第一維元素數 :',array.shape[0]) # 列數 (row number)
print('第二維元素數 :',array.shape[1]) # 行數 (column number)
print('總元素個數 :',array.size) 
print('array[0]元素的個數 :',array[0].size) 
print('元素的資料型別 :',array.dtype) # 看每個元素的資料型態
print('使用type查看元素的資料型別 :',type(array))
print('元素的位元組數 :',array.itemsize)

[[1 2 3]
 [4 5 6]] 

維度 : 2
各維度元素數 : (2, 3)
第一維元素數 : 2
第二維元素數 : 3
總元素個數 : 6
array[0]元素的個數 : 3
元素的資料型別 : int32
使用type查看元素的資料型別 : <class 'numpy.ndarray'>
元素的位元組數 : 4


## 陣列形狀 ndarray.shape

- (5, ): 為1維，即向量，例如 np.array([0, 1, 2, 3, 4])
- (5)：會被視為數字，並非tuple，所以shape會改用 (5, )
- (1, 5) :為2維，例如 np.array([[0, 1, 2, 3, 4]])

In [5]:
import numpy as np

x1 = np.array([0, 1, 2, 3, 4])
print(x1)
print('x1.shape:', x1.shape)
print()

x2 = np.array([[0], [1], [2], [3], [4]])
print(x2)
print('x2.shape:', x2.shape)
print()

x3 = np.array([[0, 1, 2, 3, 4]])
print(x3)
print('x3.shape:', x3.shape)

[0 1 2 3 4]
x1.shape: (5,)

[[0]
 [1]
 [2]
 [3]
 [4]]
x2.shape: (5, 1)

[[0 1 2 3 4]]
x3.shape: (1, 5)


# 陣列的建立

## 由其他格式轉換 np.array()

使用array()將其它格式的資料轉為陣列：
 * a = np.array([1, 3, 5, 7, 9])  
     * 將串列list轉為numpy陣列，每個元素為整數  
 * b = np.array((1, 3, 5, 7, 9))  
     * 將元組tuple轉為numpy陣列，每個元素為整數  
 * c = np.array({1, 3, 5, 7, 9})
     * 將集合set轉為numpy陣列，每個元素為物件  
 
所以：一般是使用清單或元組來建立Numpy的一維陣列

In [6]:
import numpy as np 
a = np.array([1, 3, 5, 7, 9])
b = np.array((1, 3, 5, 7, 9))
c = np.array({1, 3, 5, 7, 9})

print(a, b, c)
print()
print(type(a), type(b), type(c))   # 看整個資料的資料型態
print()
print(a.dtype, b.dtype, c.dtype)   # 看每個元素的資料型態
print()

a[3] = 0
b[3] = 0
#c[3] = 0  # 會出錯
print(a, b, c)

[1 3 5 7 9] [1 3 5 7 9] {1, 3, 5, 7, 9}

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>

int32 int32 object

[1 3 5 0 9] [1 3 5 0 9] {1, 3, 5, 7, 9}


### 在建立時指定型態

np.array(資料串, dtype=資料型態)

In [7]:
import numpy as np 
arr1 = np.array([5,2,8,4,5,6]) 
arr2 = np.array([5,2,8,4,5,6], dtype = float)
print(arr1, arr2, sep = '\n')
print(arr1.dtype, arr2.dtype)

[5 2 8 4 5 6]
[5. 2. 8. 4. 5. 6.]
int32 float64


## 固定間隔 np.arange()

* Python的range只能用在整數，np.arange可以是浮點數
* np.arange(起始值, 終止值, 間隔值, dtype=資料型態)
* 其中的參數除了終止值不可省略，其餘可以
* 和python的range()使用方法類似

In [8]:
import numpy as np 

arr1 = np.arange(5)  # 不含5
arr2 = np.arange(3, 10)
arr3 = np.arange(3, 10, 0.5)
arr4 = np.arange(3, 10, 0.8, dtype = float)
print(arr1, arr2, arr3, arr4, sep = '\n')

[0 1 2 3 4]
[3 4 5 6 7 8 9]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[3.  3.8 4.6 5.4 6.2 7.  7.8 8.6 9.4]


## 平均分布 np.linspace()

* 建立平均分布的數值  # linear space
* np.linspace(起始值, 終止值, 元素個數, dtype=資料型態)
* 使其包含起始直和終止值共有 N 個元素

In [9]:
import numpy as np

arr1 = np.linspace(0, 10, 20)  # 包含 10，注意最後一個引數是指共有20個，也就是分為19個間隔，若是要每個間隔0.5，要使用21
arr2 = np.linspace(0, 10, 21)
print(arr1, arr2, sep='\n')

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


## 亂數生成 rand(), random(), randint()

* np.random.random(元素個數)
    * 其預設值為0~1之間
* np.random.rand(第一維元素數，第二維元素數 ...)
    * 其預設值維0~1之間
* np.random.randint(起始值 = 0, 終止值, 元素個數 = 1)
    * 生成範圍不包含終止值
    * 其中的參數除了終止值不可省略，其餘可以
* 一般randint()會產生包含終止值的亂數，但numpy內的不會

In [147]:
a = np.random.random(6)

b = np.random.rand(3)
c = np.random.rand(3,3)

d = np.random.randint(1, 100, 10)
e = np.random.randint(10)

print(a, b, c, d, e, sep="\n\n")

[0.1243796  0.569078   0.40641338 0.89798891 0.69519111 0.13622993]

[0.78675306 0.86077664 0.01237618]

[[0.48329555 0.09206146 0.16153046]
 [0.24792733 0.89225967 0.04766286]
 [0.34004433 0.21053798 0.3122577 ]]

[62 98 76 27 26 87  2  3 29 55]

4


In [165]:
e = np.random.random((2,3)) #亂數，6個

In [151]:
import random

for i in range(100):
    print(random.randint(1, 3), end = " ")  # random.randint()會包含終止值3

1 3 2 2 3 1 2 1 3 3 3 3 3 3 2 2 3 2 3 3 1 3 3 1 3 1 2 1 2 2 1 1 3 2 1 1 1 3 1 1 3 1 2 1 2 1 1 3 1 1 1 1 3 2 1 2 2 2 1 3 1 3 2 3 2 2 1 2 2 2 3 2 1 1 3 3 3 1 1 2 1 3 3 2 2 1 2 3 1 2 3 2 2 1 3 3 2 2 1 1 

## 填入固定數字 zeros(), ones(), full()

* 預設資料型態為浮點數
* np.zeros(元素個數, dtype=資料型態)
    * 每個元素預設為 0
* np.ones(元素個數, dtype=資料型態)
    * 每個元素預設為 1
* np.full(元素個數, 預設值, dtype=資料型態)
* np.zeors_like(資料串)
    * 複製資料串之架構(尺寸)
    * 將其值預設為 0
* np.ones_like(資料串)
    * 複製資料串之架構(尺寸)
    * 將其值預設為 1

In [13]:
import numpy as np

a = np.zeros(6) # 數據全為0，6個
b = np.ones(6, dtype = int) # 數據為1，6個，整數
c = np.full(6, 3, dtype=float)
print(a, b, c, sep='\n')

[0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1]
[3. 3. 3. 3. 3. 3.]


In [11]:
# 用某一數字填滿整個陣列

import numpy as np

a = np.full(2, 6)  #有兩個元素，每個都是6
print(a)

print()
b = np.full((3,3), 5)
print(b)

[6 6]

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [14]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.zeros_like(a)
c = np.ones_like(a)

print(a, b, c, sep='\n\n')

[[1 2 3]
 [4 5 6]]

[[0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]]


In [ ]:
c = np.zeros((2,3)) # 數據全為0，不能用 c = np.zeros(2,3)
d = np.ones((2,3), dtype = int) # 數據為1，6個

## eye()

In [15]:
d = np.eye(3)  # 對角線都是1
print(d)

print()
e = np.eye(3, k=1)  # 從索引的1開始，對角線都是1，也就是從[0,1]的位置的斜對角開始為1
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


## 轉為立體 np.reshape()

* 將一維或多維陣列打為一維後轉換維多維陣列
* ndarray.reshape(第一維元素數，第二維元素數 ...)
* 如果元素數不足或太多會報錯
    

In [158]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)
b = np.random.randint(1, 100, 12).reshape(4,3)
c = b.reshape(6, 2)
d = np.arange(1, 16).reshape(3, 5)
print(a,b,c,d,e, sep="\n\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[76 51 72]
 [43 42  9]
 [79 91 18]
 [94 30 60]]

[[76 51]
 [72 43]
 [42  9]
 [79 91]
 [18 94]
 [30 60]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[[0.48633933 0.29014615 0.79004539]
 [0.59086589 0.32414048 0.91282415]]


### reshape() 特殊用法

- reshape(n, -1)：提供列數，行數（-1)表示自動計算行數  
    -例如b = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(4,-1)  
    - 會變成(4,2)的陣列  
- reshape(-1, n)  
    -例如b = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(-1,2)  
    - 會變成(4,2)的陣列

In [166]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(4,-1)
print(a.shape)
print(a)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 走訪陣列

In [167]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
for ele in a:
    print(ele)
    
for i in range(len(a)):
    a[i] = a[i] + 2
print(a)

1
2
3
4
5
[3 4 5 6 7]


In [168]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
for ele in a:
    print(ele)

for ele in a:
    for item in ele:
        print(item, end="  ")

[1 2]
[3 4]
[5 6]
1  2  3  4  5  6  

# 取出子陣列

* slice 取值
* 資料串[初始值 = 0 : 最終值 = n : 間隔數 = 1]
* 三種直接可省略，但不能同時全省略
* 可用負值，會由後面算起

In [171]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))    # str(a) 內容為字串 '[1 2 3 4 5 6 7 8 9]'

b = a[1:3]     # 索引 1,2
print("a[1:3]=" + str(b))
b = a[:4]      # 索引 0,1,2,3
print("a[:4]=" + str(b))
b = a[3:]      # 索引 3,4,5,6,7,8
print("a[3:]=" + str(b))
b = a[2:9:3]   # 索引 2,5,8
print("a[2:9:3]=" + str(b))
b = a[::2]     # 索引 0,2,4,6,8
print("a[::2]=" + str(b))
b = a[::-1]    # 索引 8,7,6,5,4,3,2,1,0
print("a[::-1]=" + str(b))
b = a[2:-2]    # 索引 8,7,6,5,4,3,2,1,0
print("a[2:-2]=" + str(b))

a=[1 2 3 4 5 6 7 8 9]
a[1:3]=[2 3]
a[:4]=[1 2 3 4]
a[3:]=[4 5 6 7 8 9]
a[2:9:3]=[3 4 5 6 7 8 9]
a[::2]=[1 3 5 7 9]
a[::-1]=[9 8 7 6 5 4 3 2 1]
a[2:-2]=[3 4 5 6 7]


In [22]:
# 給一個索引清單，取出選擇元素來建立新陣列

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))

print(a[0], a[2], a[-1])  # 索引 0,2,最後1個 
b = a[[1, 3, 5, 7]]       # 索引 1,3,5,7
print("a[[1,3,5,7]]=" + str(b))
b = a[range(6)]           # 索引 0,1,2,3,4,5
print("a[range(6)]=" + str(b))
a[[2, 6]] = 10            # 同時更改多個索引值
print("a[[2,6]]=10->" + str(a))

a=[1 2 3 4 5 6 7 8 9]
1 3 9
a[[1,3,5,7]]=[2 4 6 8]
a[range(6)]=[1 2 3 4 5 6]
a[[2,6]]=10->[ 1  2 10  4  5  6 10  8  9]


In [1]:
import numpy as np

a = np.arange(1, 21).reshape(4, 5)
b = a[:, 3]   # 應該是 row向量，但 Numpy 會自動轉為 collumn向量
c = a[:, 1:3]
d = a[::2, ::3]
print(a, b, c, d, sep = "\n\n")


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 4  9 14 19]

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]

[[ 1  4]
 [11 14]]
8


In [24]:
# 使用布林陣列，這是相同大小的布林值陣列，如果元素值是True，表示選擇對應的元素；反之False，就不選擇

import numpy as np

a = np.array([14,8,10,11,6,3,18,13,12,9])
print("a=" + str(a))
mask = (a % 3 == 0)        # 建立布林值陣列
print("mask=" + str(mask))
b = a[mask]                # 使用布林值陣列取出值
print("a[mask]=" + str(b))
a[a % 3 == 0] = -1         # 同時更改多個True索引
print("a[a%3==0]=-1->" + str(a))

a=[14  8 10 11  6  3 18 13 12  9]
mask=[False False False False  True  True  True False  True  True]
a[mask]=[ 6  3 18 12  9]
a[a%3==0]=-1->[14  8 10 11 -1 -1 -1 13 -1 -1]


In [25]:
# 使用複雜索引取出元素 

import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)

print()
b = a[[0,1,2],[0,1,0]]   # 索引 [0,0][1,1][2,0]
print("a[[0,1,2],[0,1,0]]=")
print(b)

print()
b = np.array([a[0,0],a[1,1],a[2,0]])  # 索引 [0,0][1,1][2,0]
print("np.array([a[0,0],a[1,1],a[2,0]])=")
print(b)

print()
idx = np.array([0, 2, 0, 1])
print("idx=" + str(idx))
b = a[np.arange(4), idx]     # 索引 [0,0][1,2][2,0][3,1]
print("a[np.arange(4),idx]=")
print(b)

print()
a[np.arange(4), idx] += 10
print("a[np.arange(4), idx] += 10->")
print(a)

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

a[[0,1,2],[0,1,0]]=
[1 5 7]

np.array([a[0,0],a[1,1],a[2,0]])=
[1 5 7]

idx=[0 2 0 1]
a[np.arange(4),idx]=
[ 1  6  7 11]

a[np.arange(4), idx] += 10->
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [26]:
# 使用整數值索引

import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
print("a=")
print(a)

print()
mask = (a > 2)
print("mask=")
print(mask)

b = a[mask]           # 使用布林值陣列取出值
print()
print("a[mask]=" + str(b))

a[a > 2] = -1         # 同時更改多個True索引
print()
print("a[a>2]=-1->")
print(a)

a=
[[1 2]
 [3 4]
 [5 6]]

mask=
[[False False]
 [ True  True]
 [ True  True]]

a[mask]=[3 4 5 6]

a[a>2]=-1->
[[ 1  2]
 [-1 -1]
 [-1 -1]]


# 改變陣列的形狀
1. 廣播:讓不同形狀的陣列執行數學運算
當一個小陣列和一個大陣列時，如果沒有廣播機制，我們需要自行先複製小陣列元素，
將它擴充成與大陣列相同的形狀後，才能執行2個陣列的數學運算，
NumPy廣播機制會自動幫我們擴充小陣列來執行運算

2. 重新設定維度: reshape()

3. 陣列平坦化: ravel()

4. 增加維度: newaxis 

In [27]:
# 廣播
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)
print("a 形狀: " + str(a.shape))

b = np.array([1,0,1])
print()
print("b=" + str(b))
print("b 形狀: " + str(b.shape))

print()
c = a + b
print('a+b:', c, sep ='\n')

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a 形狀: (4, 3)

b=[1 0 1]
b 形狀: (3,)

a+b:
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [28]:
import numpy as np
a = np.arange(0,61,10).reshape(7,1)
b = np.arange(7)
print('a:\n', a)
print('\nb:\n',b)
c = a + b
print('\na+b:\n', c)

a:
 [[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]
 [60]]

b:
 [0 1 2 3 4 5 6]

a+b:
 [[ 0  1  2  3  4  5  6]
 [10 11 12 13 14 15 16]
 [20 21 22 23 24 25 26]
 [30 31 32 33 34 35 36]
 [40 41 42 43 44 45 46]
 [50 51 52 53 54 55 56]
 [60 61 62 63 64 65 66]]


## 多維轉為一維 ravel()
* np.ravel(@ndarray)
* @ndarray.ravel()
* 陣列平坦化:將二維陣列平坦化成一維陣列, python提供兩種格式
* ravel 英文意思為解開線團

In [172]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("a=")
print(a)

b = a.ravel()
print("a.ravel()=" + str(b))
b = np.ravel(a)
print("np.ravel(a)=" + str(b))

a=
[[1 2 3]
 [4 5 6]]
a.ravel()=[1 2 3 4 5 6]
np.ravel(a)=[1 2 3 4 5 6]


## 轉置: T  OR  transpose()

In [30]:
# .T

import numpy as np

a = np.array([1,2,3,4,5,6])
print("a=" + str(a))

b = np.reshape(a,(3,2))
print("b=np.reshape(a,(3,2))->")
print(b)

print()
c = b.T
print("c=b.T->")
print(c)

print()
d = b.transpose()
print("d=b.transpose()->")
print(d)

print()
e = np.transpose(b)
print("e=np.transpose(b)->")
print(e)

a=[1 2 3 4 5 6]
b=np.reshape(a,(3,2))->
[[1 2]
 [3 4]
 [5 6]]

c=b.T->
[[1 3 5]
 [2 4 6]]

d=b.transpose()->
[[1 3 5]
 [2 4 6]]

e=np.transpose(b)->
[[1 3 5]
 [2 4 6]]


In [32]:
# newaxis 增加維度

import numpy as np

a = np.array([1,2,3])
print("a=" + str(a))

print()
b = a[:, np.newaxis]
print("b=a[:,np.newaxis]->")
print(b)
print('shape:', b.shape)

print()
c = a[np.newaxis, :]
print("c=a[np.newaxis,:]->")
print(c)
print('shape:', c.shape)

a=[1 2 3]

b=a[:,np.newaxis]->
[[1]
 [2]
 [3]]
shape: (3, 1)

c=a[np.newaxis,:]->
[[1 2 3]]
shape: (1, 3)


# 陣列的複製

In [31]:
a1 = [1, 2, 3]
b1 = a1
b1[2] = 10
print(a1, b1)

[1, 2, 10] [1, 2, 10]


In [33]:
# 陣列形狀與內容操作 –陣列複製、填滿值和連接陣列

import numpy as np

a = np.array([1,2,3])
print("a=" + str(a))

b = a.copy()   # 不使用 b = a，a和b會指向同一個位址，修改內容時，兩者的內容都會一起改變
print("b=a.copy()->" + str(b))
b.fill(4)
print("b.fill(4)=" + str(b))
c = np.concatenate((a,b))
print("c=np.concatenate((a,b))->" + str(c)) # 


a=[1 2 3]
b=a.copy()->[1 2 3]
b.fill(4)=[4 4 4]
c=np.concatenate((a,b))->[1 2 3 4 4 4]


In [34]:
a = np.array([1,2,3])
b = a    # 用這種方式設定，a和b會指向同一個位址，修改內容時，兩者的內容都會一起改變，所以若是一般的複製，會使用 b = a.copy()
b[0] = 5
print(a)

[5 2 3]


# 陣列的運算

## universal function (簡稱 ufunc) universal函式

* 意義：NUmpy提供對陣列中全部元素進行運算，並有回傳功能的函式
* 例如：np.sum(), np.square(), np.sin()...

* 註：使用以下方法，在type中可以看到是否屬於ufunc
    * numpy.函式名稱?


In [35]:
import numpy as np

np.sin?

In [36]:
# 陣列與常數的運算

import numpy as np
a=np.array([[3,6,9],[12,15,18]])
b = a +3
print(b)

[[ 6  9 12]
 [15 18 21]]


In [37]:
#兩個陣列的加減乘除法 (*非矩陣乘法*)
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
b=np.arange(1,7).reshape((2,3)) 
print("a:\n", a)
print("\nb:\n", b)
print("\na+b:\n", a+b)
print("\na-b:\n", a-b)
print("\na*b:\n", a*b)
print("\na/b:\n", a/b)

a:
 [[ 2  4  6]
 [ 8 10 12]]

b:
 [[1 2 3]
 [4 5 6]]

a+b:
 [[ 3  6  9]
 [12 15 18]]

a-b:
 [[1 2 3]
 [4 5 6]]

a*b:
 [[ 2  8 18]
 [32 50 72]]

a/b:
 [[2. 2. 2.]
 [2. 2. 2.]]


In [38]:
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
a = a ** 2  # 平方
print(a)

print()
print(a>10)

[[  4  16  36]
 [ 64 100 144]]

[[False  True  True]
 [ True  True  True]]


## 矩陣乘法 dot()

In [39]:
# 矩陣乘法 numpy.dot()
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
b=np.arange(6).reshape((2,3)) 
print(a)
print(b.T) # transpose
print(np.dot(a,b.T))

[[ 2  4  6]
 [ 8 10 12]]
[[0 3]
 [1 4]
 [2 5]]
[[ 16  52]
 [ 34 124]]


## sum()

In [40]:
# 我們可以指定參數axis軸的連接方向，參數值0是直向，可以連接在二維陣列的下方；值1是橫向
import numpy as np
a=np.array([[3,6,9],[12,15,18]])

print(a)
print()
print("sum(a):", np.sum(a))
print("sum(a, axis=1):",np.sum(a, axis=1))

print("sum(a, axis=0):",np.sum(a, axis=0))

print(a.sum(axis = 1))

[[ 3  6  9]
 [12 15 18]]

sum(a): 63
sum(a, axis=1): [18 45]
sum(a, axis=0): [15 21 27]
[18 45]


## 合併&增加  concatenate()
* concatenate() 可以合併兩個陣列或加入元素

In [41]:
# 使用np.concatenate()函數連接多個二維陣列時，
# 我們可以指定參數axis軸的連接方向，參數值0是直向，可以連接在二維陣列的下方；值1是橫向，預設為0

import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.concatenate((a,b))
print("c=np.concatenate((a,b))->")
print(c)
c = np.concatenate((a,b), axis=0)
print("c=np.concatenate((a,b), axis=0)->")
print(c)
c = np.concatenate((a,b), axis=1)
print("c=np.concatenate((a,b), axis=1)->")
print(c)

c=np.concatenate((a,b))->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=0)->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=1)->
[[1 2 5 6]
 [3 4 7 8]]


In [42]:
import numpy as np
a = np.array([2,4,6,8,10,12])
b = np.arange(10)
c = np.concatenate((a,b))
d = np.concatenate((a,[10,20]))
print(a,b,c,d, sep="\n\n")

[ 2  4  6  8 10 12]

[0 1 2 3 4 5 6 7 8 9]

[ 2  4  6  8 10 12  0  1  2  3  4  5  6  7  8  9]

[ 2  4  6  8 10 12 10 20]


In [43]:
# Numpy array 合併

import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])

print(np.vstack((A,B))) #vertical

print(np.hstack((A,B))) #horizontal, 和np.concatenate((A, B), axis=0)一樣

c = np.concatenate((A, B), axis=0)
print(c)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[1 1 1 2 2 2]


## 排序 sort()

In [44]:
# 值的排序有兩種
# np.sort(a, ...)   -> 傳回排序後的陣列，變數本身的值不會改變
# a.sort()   -> 變數本身的值會改變
# sort 可以指定排序的方法(使用 kind參數設定)：quick sort, bubble sort, heap sort....

import numpy as np

a = np.random.randint(1, 100, (4, 5))
print(a)

print('\nb = np.sort(a, axis = 1):\n')
b = np.sort(a, axis = 1) # 同一列內做排序
print(b)

print('\na:\n')
print(a)   # 原來的內容不變

print('\na.sort(axis = 1)之後a的值改變了：\n')
a.sort(axis = 1)
print(a)

[[80 34 14 60 42]
 [48  6 89 91 62]
 [16 34 37 34 22]
 [58 58 81  1 51]]

b = np.sort(a, axis = 1):

[[14 34 42 60 80]
 [ 6 48 62 89 91]
 [16 22 34 34 37]
 [ 1 51 58 58 81]]

a:

[[80 34 14 60 42]
 [48  6 89 91 62]
 [16 34 37 34 22]
 [58 58 81  1 51]]

a.sort(axis = 1)之後a的值改變了：

[[14 34 42 60 80]
 [ 6 48 62 89 91]
 [16 22 34 34 37]
 [ 1 51 58 58 81]]


In [45]:
np.sort?

# Numpy的亂數

* 格式為： numpy.random.亂數的方法()

* seed(int) : 指定亂數函數的種子數，這是整數值，同一個種子數會產生相同的亂數序列
 * seed(5)
* random() : 產生0.0~1.0之間的亂數，如 0.7298076072029743
 * random(5):產生0.0~1.0之間的亂數5個，形成5個元素的串列，如[ 0.58607119  0.37147243  0.05337405  0.49300567  0.10304672]
 * random((3,4)))：產生二維陣列的亂數

* randint(min,max,size) : 產生min~max之間的整數亂數，不含max，如果有第3個參數可以產生此形式的陣列
 * randint(5, 10)：產生5~10之間的整數亂數，不含10
 * randint(5, 10, 6)：產生產生5到10(不含)的整數6個的陣列　[8 7 6 8 6 6]
 * randint(1, 101, (3,4))：產生5到10(不含)的整數3*4個的二維陣列
<pre>
[[ 52  61 100  23]
 [ 18  76   5  85]
 [ 99  96  93  57]] </pre>
 
* rand()： 可以產生亂數值或是多維的陣列
 * rand()：產生0至1之間的小數亂數，例如　0.9760298522559884
 * rand(5)： 5個亂數值的串列，例如：[ 0.64355233  0.06190279  0.0139926   0.49136906  0.18873564]
 * rand(3,2,4)：三維的亂數
<pre>
[[[ 0.03954012  0.44242043  0.14827974  0.56508804]
  [ 0.81026024  0.35193408  0.67416147  0.3857823 ]]

 [[ 0.75199775  0.68688449  0.11550551  0.74191692]
  [ 0.59480112  0.6741724   0.83223916  0.07394322]]

 [[ 0.56966074  0.50914309  0.80103979  0.99366129]
  [ 0.57323325  0.15629903  0.39392062  0.98063935]]] </pre>

* np.random.randn(): 類似rand()，可以產生標準常態分佈的樣本資料
* np.random.normal(loc=xx, scale=xx, size=xx)：功能如同.randn()，但是可以產生各種常態分布的資料，且可以產生亂數的陣列 (loc 為平均數，預設為0，scale為標準差，預設為1，xx表示自由輸入的數字）
 * np.random.normal(10,3,5)  # 產生5個平均數為 10，標準差為 3 的常態分布的亂數
 * np.random.normal(10,3,(2,4)) # 產生二維陣列平均數為 10，標準差為 3 的常態分布的亂數 （共有2*4個）
 
* np.random.choice()
    * 参数意思分别 是从a 中以概率P，随机选择3个, p没有指定的时候相当于是一致的分布，replace = True 表示放回再抽
    * a = list(range(1, 7))
    * print(a)
    * a1 = np.random.choice(a, size=3, replace=False, p=None)
* np.random.shuffle(串列) 
    * 將串列打亂

原文網址：https://kknews.cc/zh-tw/other/29er599.html


In [46]:
# random.randint() 與 numpy.random.randint()之差異
import numpy as np
import random

throws1 = np.random.randint(0, 2)  # exclude 2
throws2 = random.randint(0,2)  # include 2

throws3 = np.random.randint(low=0, high=2, size=10) # 100 random numbers
throws4 = np.random.randint(0, 2, 10)  # 10 random numbers, no argument names
throws5 = np.random.randint(0, 2, (3,4))
print("throws1:", throws1)
print("throws2:", throws2)
print("throws3:", throws3)
print("throws4:", throws4)
print("throws5:", throws5)

throws1: 1
throws2: 2
throws3: [1 0 1 1 1 0 1 0 0 0]
throws4: [0 1 0 1 0 1 1 1 0 0]
throws5: [[1 0 0 1]
 [1 0 0 0]
 [1 1 1 1]]


In [47]:
import numpy as np
print(np.random.rand())
print()

print(np.random.rand(5)) # 5個亂數值的串列
print()

print(np.random.rand(3,2,4))  # 三維的亂數

0.6541953333272281

[0.38391355 0.16245223 0.17389961 0.82431291 0.39278555]

[[[0.82395443 0.22169704 0.76577035 0.73127241]
  [0.13391873 0.206846   0.70728369 0.09727872]]

 [[0.84013279 0.14432041 0.82287406 0.44073119]
  [0.97393275 0.9986436  0.90859196 0.27461394]]

 [[0.26861292 0.60649151 0.30834071 0.74765184]
  [0.78077861 0.73837961 0.34245072 0.45397828]]]


In [48]:
import numpy as np
a = np.random.random()
b = np.random.random(5)
print(a, b, c, sep = '\n\n')

0.7084478557032612

[0.18558948 0.20123812 0.64462511 0.89941859 0.32493393]

[1 1 1 2 2 2]


In [49]:
import numpy as np

np.random.seed(293423)

v1 = np.random.random()
v2 = np.random.random()
print(v1, v2)
v3 = np.random.randint(5, 10)  #產生5到10(不含)的整數
v4 = np.random.randint(1, 101)
print(v3, v4)

print()
v5 = np.random.randint(5, 10, 6) # 產生5到10(不含)的整數6個的陣列
v6 = np.random.randint(1, 101, (3,4))#  產生5到10(不含)的整數3*4個的二維陣列
print(v5)
print()
print(v6)
?v6

0.3367724725390667 0.5269343749958971
6 46

[8 7 6 8 6 6]

[[ 52  61 100  23]
 [ 18  76   5  85]
 [ 99  96  93  57]]


In [50]:
import numpy as np
print(np.random.rand())
print()

print(np.random.randn(5)) # 產生標準常態分佈的樣本資料的5個亂數值的串列
print()

print(np.random.randn(3,2,4))  # 三維的亂數

0.4648092770600095

[-1.08476786  2.0339594  -0.40370633 -0.48121807 -0.41510009]

[[[-1.87786529 -1.27974244  0.43870783 -0.25717143]
  [ 0.73472129  0.07402115  1.73449681  1.88650179]]

 [[ 0.02389854  0.34381783  0.73768333 -0.28236147]
  [ 0.23572273 -0.69830466  0.06320116  0.39744967]]

 [[-2.29596826  0.31087695 -0.80067897 -1.08690637]
  [ 1.50062876 -1.04275225 -1.60816675  0.3814968 ]]]


In [51]:
import numpy as np

a = np.random.rand(5)
print("np.random.rand(5)=")
print(a)

print()
b = np.random.rand(3, 2)  
print("np.random.rand(3,2)=")
print(b)

print()
c = np.random.randint(5, 10, size=5)
print("np.random.randint(5,10,size=5)")  # size =  可以省略
print(c)

print()
d = np.random.randint(5, 10, size=(2,3))
print("np.random.randint(5,10,size=(2,3))")  # size =  可以省略，如下面的敘述
print(d)

print()
d = np.random.randint(5, 10, (2,3))
print("np.random.randint(5,10,size=(2,3))") 
print(d)

np.random.rand(5)=
[0.72980761 0.58607119 0.37147243 0.05337405 0.49300567]

np.random.rand(3,2)=
[[0.10304672 0.6202105 ]
 [0.0733859  0.86405515]
 [0.23368263 0.78149921]]

np.random.randint(5,10,size=5)
[9 6 6 6 5]

np.random.randint(5,10,size=(2,3))
[[6 5 6]
 [6 5 8]]

np.random.randint(5,10,size=(2,3))
[[6 9 9]
 [7 7 7]]


In [52]:
# choice 的使用
# 参数意思分别 是从a 中以概率P，随机选择3个, p没有指定的时候相当于是一致的分布，replace = True 表示放回再產生(預設為True)

import numpy as np

print(np.random.choice(10, 10, replace = False)) # 產生 0至 9不重複的整數亂數 10個

a = list(range(1, 7))
a1 = np.random.choice(a, size=3, replace=False, p=None)  # 產生 1至 6不重複的整數亂數 3個
print(a1)

print()
a2 = np.random.choice(a=range(1, 85), size=84, replace=False, p=None).reshape(21,4) # 將 1-84的數字用亂數來分組，每4個一組
print(a2)

[9 8 0 5 2 4 3 7 6 1]
[3 1 4]

[[16 49 74  4]
 [68 36  5 58]
 [37 51 15 48]
 [82 84 14 20]
 [35 45 21 57]
 [27 24 38  9]
 [70 40 31 80]
 [28 65 60 46]
 [ 2 61 83 59]
 [67  8 71 55]
 [19 22 29 25]
 [11  7 12 43]
 [33 17 64 72]
 [18 69 75 79]
 [63 73 44 26]
 [76 78 42 77]
 [30 54 52 10]
 [13 41 62 39]
 [81 34  1 53]
 [32  6 66 50]
 [47  3 56 23]]


# NumPy的通用函式

## NumPy針對陣列提供許多通用函式，例如：
* add(x1, x2) 
* subtract(x1, x2) 
* multiply(x1, x2) 
* divide(x1, x2) 
* mod(x1, x2) 
* power(x1, x2)
* isfinite(x) 
* isinf(x) 
* isnan(x) 
* sign(x)
* negative(x) 
* absolute(x) 
* sum(x) 
* max(x) 
* min(x) 

* rint(x) 
* floor(x) 
* ceil(x) 
* sqrt(x) 
* square(x) 
* exp(x) 
* exp2(x) 
* log(x) 
* log2(x) 
* log10(x) 
* cos(x)、sin(x)、tan(x)、acos(x)、asin(x)、atan(x) 等三角函式
* mean(x) 
    * 含遺漏值的平均數：np.mean(dataframe物件或欄位)
    * 不含遺漏值的平均數： np.nanmean(dataframe物件或欄位)
* median(x)  中位數
    * 含遺漏值的中數：np.median(dataframe物件或欄位)
    * 不含遺漏值的中數： np.nanmedian(dataframe物件或欄位)
* std(x)
    * 分為母數推估和樣本的標準差兩種，參見統計課程中的講義


In [53]:
# 三角函式

import numpy as np

a = np.array([30,45,60]) 

print(np.sin(a*np.pi/180)) 
print(np.cos(a*np.pi/180)) 
print(np.tan(a*np.pi/180)) 

[0.5        0.70710678 0.8660254 ]
[0.8660254  0.70710678 0.5       ]
[0.57735027 1.         1.73205081]


In [54]:
# numpy 平均數的用法

import numpy as np
a = [[1,2,3], [4,5,6]]
print(np.mean(a))
print(np.mean(a, axis = 0))
print(np.mean(a, 0))
print(np.mean(a, axis = 1))
print(np.mean(a, 1))

3.5
[2.5 3.5 4.5]
[2.5 3.5 4.5]
[2. 5.]
[2. 5.]


# 檔案儲存與載入

In [56]:
# 將陣列儲存成檔案


In [57]:
# 使用二進位檔寫入， 使用save

import numpy as np

a = np.arange(10)
outputfile = "Example.npy"
with open(outputfile, 'wb') as fp:
    np.save(fp, a)

In [58]:
#  設定分隔字元，delimiter=','
# savetxt 儲存成 CSV格式
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
outputfile = "Example.out"
np.savetxt(outputfile, a, delimiter=',')

In [59]:
# Example.out
1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00

(4.0, 5.0, 6.0)

In [60]:
#  設定分隔字元，delimiter=','
# savetxt 儲存成 CSV格式
import numpy as np

a = np.array([[1,2,3],[4,5,6]], dtype = int)
outputfile = "Example.out"
np.savetxt(outputfile, a, delimiter=',')
print(a)

[[1 2 3]
 [4 5 6]]


In [61]:
# Example.out
1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00

(4.0, 5.0, 6.0)

In [62]:
# 使用二進位檔讀入， 使用load
import numpy as np

outputfile = "Example.npy"
with open(outputfile, 'rb') as fp:
    a = np.load(fp)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
# 使用CSV檔讀入， 使用loadtxt
import numpy as np

outputfile = "Example.out"
a = np.loadtxt(outputfile, delimiter=',')
print(a)
print()

b = a.astype(int)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]

[[1 2 3]
 [4 5 6]]


# Numpy陣列的記憶體位置

In [64]:
# 設定變數等於另一串列變數，更改數值時，原變數也會改變，因為兩個串列的位址相同

import numpy as np
a = np.array([1, 3, 5])
b = a
b[2] = 10
print(a, b)
print(id(a), id(b))

[ 1  3 10] [ 1  3 10]
2558245083056 2558245083056


In [65]:
# 拷貝串列的值給新的變數的方式 (tuple, dic等進階資料型態亦同)

a = np.array(range(10))
# 方法一
b = a[:]

# 方法二
c = a.copy()

print(a, b, c, sep = '\n')
print('\n', id(a), id(b), id(c), sep = '\n')


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


2558245083632
2558245084016
2558245083056


In [66]:
# 判斷是否使用共同的記憶體
# np.may_share_memory()

a = np.array(range(10))
# 方法一
b = a[:]

# 方法二
c = a.copy()
d = a

print('a, b ->', np.may_share_memory(a, b))
print('a, c ->', np.may_share_memory(a, c))
print('a, d ->', np.may_share_memory(a, d))

a, b -> True
a, c -> False
a, d -> True


# 12. 多項式

- numpy.poly1d(多項式的係數數列)   
    - poly＋數字1 + d

In [67]:
import numpy as np

p = np.poly1d([1, 3, 2])   # 二次多項式的係數
print('多項式的根:', p.roots)   # 多項式的根
print('次方數:', p.order)   # 次方數
print('係數:', p.coeffs)  # 係數

多項式的根: [-2. -1.]
次方數: 2
係數: [1 3 2]


## 參考書目：

- 陳允傑（2018）。Python資料科學與人工智慧應用實務。 台北：旗標。
- 黃永昌（2019）。打下最紮實的AI基礎：從scikit-learn：一步一腳印。台北：佳魁數位。