numpy or pandas

English:

Note: The PIPLS environment does not have Numpy or Pandas, please use the Code function to paste your source code, and upload your CSV file. This question will be revised by TA.

Data Link

Attached is a CSV file recording the grade of a programming class, the file description is as follows.

<img src="img/q1.png">

1.  1~10 represents a total of ten students.

2.  A~G are the grades of each question in the first mid-term examination. The first four questions (A~D column) each question count for 10% of the midterm grade and the last three questions (E~G column) each question count for 20% of the midterm grade.

EX: The first student's first mid-term exam results were: (60 * 0.1)+(0 * 0.1)+(0 * 0.1)+(0 * 0.1)+(40 * 0.2)+(40 * 0.2 )+(30 * 0.2) = 28(points)

H~N are the grades of each question in the second mid-term exam grades, and the grades are calculated in the same way.

O~U are the grades of each question in the third mid-term exam grades, and the grades are calculated in the same way.

<img src="img/q1_2.png">
3.  V~AE is the attendance record, 0 means absence from class, 1 means attendance the class, each attendance record counts for 10 poin of the attendance record grade. (That is, 10 points for coming to class once and getting a attendance record grade)

4.  Total semester grade = 1st midterm * 0.3 + 2nd midterm * 0.3 + 3rd midterm * 0.3 + point score * 0.3. If the total score exceeds 100 points, it will be calculated as a maximum of 100 points.

Now, using the relevant functions in Numpy or Pandas, please complete the following:

1.  Read this CSV file  

2.  Calculate each student's mid-term exam results and total semester grades(your result shape should be 10x4)

3.  Write the calculate result to a CSV file

4.  Upload your Code and CSV files to PIPLS

sameple result
<img src="img/q1_3.png">


中文：

注意：PIPLS環境沒有Numpy、Pandas，請用問答的Code功能貼上你的原始碼，並上傳CSV檔，助教會手動批改。

Data Link

附檔是一份紀錄某程式設計班級成績的CSV檔案，檔案敘述如下：

1.  1~10代表總共有10位學生

2.  A~G為第一次期中考各題成績，前四題(A~D)每題佔期中考成績10%，後三題(E~G)每題佔期中考成績20%。

EX:第一位學生第一次期中考成績為：60 * 0.1+0 * 0.1+0 * 0.1+0 * 0.1+40 * 0.2+40 * 0.2 + 30 * 0.2 = 28(分)

H~N為第二次期中考成績，O~U為第三次期中考成績，成績計算方式依此類推

3.  V~AE為點名，0代表缺課，1代表有來上課，每次點名佔點名成績10%(即有來上課一次得點名成績10分)

4.  學期總成績 = 第一次期中考 * 0.3 + 第二次期中考 * 0.3 + 第三次期中考 * 0.3 + 點名 * 0.3，
    如果成績總分大於100分，則以最高100分計算。

現在請你使用Numpy或Pandas套件裡相關函數，完成以下事項：

1.  讀取此CSV檔

2.  計算出每位學生的每次期中考成績與學期總成績(你的結果應為10x4的矩陣)

3.  將2.的計算結果寫入CSV檔

4.  上傳你的Code與CSV檔至PIPLS

In [1]:
import numpy as np
import pandas as pd

a = np.loadtxt("data_q1.csv", delimiter=',')

print(a)
b = a.astype(int)
print(b)
res = np.full((10,4), 0)
for i in range(10):
    res[i, 0] = b[i, 0] * 0.1 + b[i, 1] * 0.1 + b[i, 2] * 0.1 + b[i, 3] * 0.1 + b[i, 4] * 0.2 + b[i, 5] * 0.2 + b[i, 6] * 0.2
    res[i, 1] = b[i, 7] * 0.1 + b[i, 8] * 0.1 + b[i, 9] * 0.1 + b[i, 10] * 0.1 + b[i, 11] * 0.2 + b[i, 12] * 0.2 + b[i, 13] * 0.2
    res[i, 2] = b[i, 14] * 0.1 + b[i, 15] * 0.1 + b[i, 16] * 0.1 + b[i, 17] * 0.1 + b[i, 18] * 0.2 + b[i, 19] * 0.2 + b[i, 20] * 0.2
    
    res[i, 3] = res[i, 0] * 0.3 + res[i, 1] * 0.3 + res[i, 2] * 0.3
    for j in range(21, 31):
        res[i, 3] += b[i, j] * 3
    
print(res)

np.savetxt('result.csv', res, delimiter=',')

[[ 60.   0.   0.   0.  40.  40.  30.  90.  90.  70. 100.  70.  50.   0.
    0.  10.  50.  40.  40.  50.  40.   0.   1.   1.   1.   1.   1.   1.
    1.   1.   1.]
 [100.  90.  40.  40.  60.  80.  70.  70.  10.  40.  30.  60.  80.  60.
   90.  80.  40.  50.  50.  80.  70.   1.   1.   1.   1.   1.   1.   1.
    1.   1.   1.]
 [ 10.  20.  90.  60.  60. 100.  20.  90.  10.  60.  70.  90. 100.  40.
   80.  90.  30.  30.  80.  10.  70.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.]
 [ 10.  50.  40.  90.  90.  40.   0.  70.  60.  60.  70.  30.  30.  70.
   60.  40.  50.  40.   0.  50.  40.   1.   1.   1.   0.   0.   1.   1.
    1.   0.   1.]
 [  0.   0. 100.  60.  20.  30.  30.  30.  30.   0.  50.   0.   0.  20.
   10.  70.  70.   0.  90.  80.  60.   1.   0.   0.   0.   0.   0.   0.
    0.   0.   0.]
 [ 90.  60.  80.  60.  70.  20.  70.  80.  20.  50.   0.  30.  70.  50.
   70.  50.   0.  40.  40.  20.  50.   1.   0.   1.   0.   0.   0.   1.
    1.   1.   1.]
 [ 80.  70.  40.   0.  30.  

In [4]:
import numpy as np



import pandas as pd



df = pd.read_csv("data_q1.csv", header=None, encoding="utf8")



midterm1 = []



midterm2 = []



midterm3 = []



total = []



for student in df.index:



    m1 = (df.iloc[student, 0] * 0.1) + (df.iloc[student, 1] * 0.1) +(df.iloc[student, 2] * 0.1) +(df.iloc[student, 3] * 0.1) + (df.iloc[student, 4] * 0.2) + (df.iloc[student, 5] * 0.2) + (df.iloc[student, 6] * 0.2)



    m2 = (df.iloc[student, 7] * 0.1) + (df.iloc[student, 8] * 0.1) +(df.iloc[student, 9] * 0.1) +(df.iloc[student, 10] * 0.1) + (df.iloc[student, 11] * 0.2) + (df.iloc[student, 12] * 0.2) + (df.iloc[student, 13] * 0.2)



    m3 = (df.iloc[student, 14] * 0.1) + (df.iloc[student, 15] * 0.1) +(df.iloc[student, 16] * 0.1) +(df.iloc[student, 17] * 0.1) + (df.iloc[student, 18] * 0.2) + (df.iloc[student, 19] * 0.2) + (df.iloc[student, 20] * 0.2)



    a = df.iloc[student, 21] + df.iloc[student, 22] + df.iloc[student, 23] +df.iloc[student, 24] + df.iloc[student, 25] + df.iloc[student, 26] + df.iloc[student, 27] +df.iloc[student, 28] +df.iloc[student, 29] +df.iloc[student, 30]



    



    grade = (m1 * 0.3) + (m2 * 0.3) + (m3 * 0.3) + a



    midterm1.append(m1)



    midterm2.append(m2)



    midterm3.append(m3)



    total.append(grade)



    



result = np.column_stack((midterm1, midterm2, midterm3, total))



print(result)

[[28.  59.  36.  45.9]
 [69.  55.  66.  67. ]
 [54.  69.  55.  53.4]
 [45.  52.  37.  47.2]
 [32.  15.  61.  33.4]
 [61.  45.  38.  49.2]
 [45.  75.  63.  62.9]
 [59.  29.  62.  49. ]
 [54.  39.  49.  47.6]
 [36.  62.  36.  44.2]]
